Feature/mon 66 avatar
22-reactors/monopoly pull request #14
Opened 2023-02-12 13:41 UTC by Krezo

Компонент смены аватара

2023-02-12 19:22 UTC, Krezo commented
На конфлиты прошу внимания не обращать. Разрешу, когда зальют в dev фиксы билда проекта

2023-02-14 07:51 UTC, nullorone commented on packages/client/src/components/avatar/avatar.tsx
> +      // Запрос к API
отображать сразу аватар не будем? Будет лишний запрос, если мы сначала отправим изменение аватара, а потом сразу получим измененные данные пользователя

2023-02-14 07:52 UTC, nullorone commented on packages/client/src/components/avatar/avatar.tsx
> +  const openBrowserAvatarFile = () => {
инпут с типом file по умолчанию откроет окно выбора файла. Зачем эта логика через реф, не совсем понимаю

2023-02-14 07:53 UTC, nullorone commented on packages/client/src/components/avatar/avatar.tsx
> +        className={classNames(style.avatar)}></div>
classNames здесь лишнее

2023-02-14 07:54 UTC, nullorone commented on packages/client/src/components/avatar/avatar.tsx
> +      <button onClick={openBrowserAvatarFile} className={style.button}>
если добавить label и связать с input через id,  то эта кнопка не потребуется

2023-02-14 08:11 UTC, nullorone commented
не соответствует макету

<img width="151" alt="image" src="https://user-images.githubusercontent.com/35527172/218676941-aa26afbe-53c3-4ca3-b758-fa76c4867993.png">

2023-02-14 08:13 UTC, nullorone commented on packages/client/src/components/avatar/avatar.tsx
> +  const avatarSize = {
зачем нам нужна такая возможность установки размеров аватара?

2023-02-14 08:15 UTC, nullorone commented on packages/client/src/components/avatar/avatar.tsx
> +    <section className={style.container}>
[Рекомендация]
Лучше обернуть в form, тогда, даже при неработающем js у пользователя, прописав адрес в action к апи изменения аватара, запрос уйдет и аватарка изменится

2023-02-14 13:16 UTC, Krezo commented on packages/client/src/components/avatar/avatar.tsx
> +  const openBrowserAvatarFile = () => {
Инпут скрыт, поэтому чтобы открыть окно выбора файла нужно его тригернуть

2023-02-15 20:30 UTC, Krezo commented on packages/client/src/components/avatar/avatar.tsx
> +      // Запрос к API
С API  в ответе прилетает ссылка на картику

2023-02-15 22:33 UTC, Krezo commented on packages/client/src/components/avatar/avatar.tsx
> +        className={classNames(style.avatar)}></div>
Убрал

2023-02-15 22:34 UTC, Krezo commented on packages/client/src/components/avatar/avatar.tsx
> +      <button onClick={openBrowserAvatarFile} className={style.button}>
Думаю, это не критично

2023-02-15 22:34 UTC, Krezo commented on packages/client/src/components/avatar/avatar.tsx
> +  const avatarSize = {
Убарл

2023-02-15 23:11 UTC, Krezo commented on packages/client/src/components/avatar/avatar.tsx
> +  const openBrowserAvatarFile = () => {
> не соответствует макету
> 
> <img alt="image" width="151" src="https://user-images.githubusercontent.com/35527172/218676941-aa26afbe-53c3-4ca3-b758-fa76c4867993.png">

Теперь все ок

![image](https://user-images.githubusercontent.com/19520555/219212248-b3a53388-7db5-4eb5-8b8a-3d7d45b03ca0.png)

2023-02-16 12:16 UTC, nullorone commented on packages/client/src/components/avatar/avatar.tsx
> +    height: '150px',
Поясни плиз, почему размеры контейнера заданы не через стили?

2023-02-16 12:25 UTC, nullorone requested changes
С размерами не в стилях остался вопрос

2023-02-20 13:45 UTC, Krezo commented
Переместил размеры в стили

2023-02-20 14:47 UTC, nullorone commented on packages/client/src/components/avatar/avatar.tsx
> +    ...avatarSize,
Если размеры теперь в стилях, то отсюда их надо удалить?

2023-02-20 14:48 UTC, nullorone requested changes
Нужно удалить лишнее

2023-02-21 08:05 UTC, Krezo commented
> Нужно удалить лишнее

Вроде убирал, только не понял, почему код старый остался. Исправил

2023-02-21 08:08 UTC, nullorone approved these changes

2023-02-21 09:38 UTC, kate-lozovaya approved these changes
Вот такая история коммитов - не очень хорошо, с ней труднее ориентироваться по проекту. Лучше такие коммиты склеивать, это можно делать через `git rebase -i HEAD~<количество коммитов>`.
И очень не хватает скринов. 

<img width="505" alt="image" src="https://user-images.githubusercontent.com/25737137/220306067-b7411855-3c09-4fba-8ce1-2d1df64ac9df.png">

2023-02-21 10:24 UTC, merged