Feature/mon 56 textarea
22-reactors/monopoly pull request #15
Opened 2023-02-12 17:21 UTC by Krezo

Реализация компонент textarea

Задача: https://linear.app/monopoly/issue/MON-56/sverstat-komponent-textarea

2023-02-12 19:21 UTC, Krezo commented
На конфлиты прошу внимания не обращать. Разрешу, когда зальют в dev фиксы билда проекта

2023-02-14 21:39 UTC, realdmitrii approved these changes
пардон что долго(
в основном шрифты в этом PR-вопросов нет
только по index.ts - обсуждали ведь это в пачке, у всех работает с этим
с другой стороны, Яр сказал что если мешает- убирай. так что апрув, там уже ревьюер пусть принимает решение)

2023-02-14 21:39 UTC, realdmitrii commented on packages/server/index.ts
> +// createClientAndConnect();
предлагаю не комментить, с этим сервер запускается у меня

2023-02-15 20:24 UTC, Krezo commented on packages/server/index.ts
> +// createClientAndConnect();
Комментирование для vercel, он не не деплоит проект

2023-02-16 09:13 UTC, kate-lozovaya requested changes

2023-02-16 09:13 UTC, kate-lozovaya commented on packages/client/src/types/validation.ts
> +  errorText?: string | boolean;
[Вопрос]
Почему переменная может быть и `string`, и `boolean`, и `undefined`?
Не подойдет ли значение `undefined` как альтернатива для `boolean`?

2023-02-16 09:13 UTC, kate-lozovaya commented on packages/client/src/components/textarea/textarea.tsx
> +  placeholder?: string;
[Исправление]
Есть возможность передать placeholder, но он никак не будет использован

2023-02-16 09:13 UTC, kate-lozovaya commented on packages/client/src/components/textarea/textarea.tsx
> +  const textateaStyle = {
[Исправление]
Опечатка `textateaStyle` -> `textareaStyle`

2023-02-16 09:13 UTC, kate-lozovaya commented on packages/client/src/components/textarea/textarea.tsx
> +    resize: resize || 'vertical',
[Исправление]
Проверяешь переменную `resize` на `undefined`, лучше использовать ?? - `resize ?? 'vertical'`
[Примеры со стековерфлоу](https://stackoverflow.com/questions/66883181/difference-between-and-operators)

2023-02-16 09:13 UTC, kate-lozovaya commented on packages/client/src/components/textarea/textarea.tsx
> +  const isValid = !!errorText;
[Предложение]
`!!undefined = false`, можно оставить только тип `string` для интерфейса `IValidationInputProps?: string`

2023-02-16 09:13 UTC, kate-lozovaya commented on packages/client/src/components/textarea/textarea.tsx
> +    }
[Предложение]
Можно сократить запись до 
```suggestion
    !value && setLabelFocus(false);
    onBlur && onBlur(event);
```

2023-02-16 09:13 UTC, kate-lozovaya commented on packages/client/src/components/textarea/textarea.tsx
> +        placeholder={(solo && label) || ''}
[Вопрос]
Получается, что если есть `label`, он и в `placeholder` и в `label` в 63-66 строках будет?

2023-02-16 09:13 UTC, kate-lozovaya commented on packages/client/src/components/textarea/textarea.module.scss
> +  background: #fff;
[Вопрос]
А в проекте есть переменные для цветов?

2023-02-16 09:13 UTC, kate-lozovaya commented on packages/client/src/components/textarea/textarea.module.scss
> +      color: $text-error !important;
[Вопрос]
`!important - зло! `
Потом переопредилить стили будет нереально. Он тут точно нужен?

2023-02-16 09:13 UTC, kate-lozovaya commented on packages/client/src/components/textarea/textarea.module.scss
> +      color: $text-error !important;
[Вопрос]
И снова зло!
Вопрос тот же, точно ли тут нужен `!important`?

2023-02-20 09:14 UTC, Krezo commented on packages/client/src/types/validation.ts
> +  errorText?: string | boolean;
Поправил

2023-02-20 09:15 UTC, Krezo commented on packages/client/src/components/textarea/textarea.tsx
> +  placeholder?: string;
Убрал из пропсов

2023-02-20 09:16 UTC, Krezo commented on packages/client/src/components/textarea/textarea.tsx
> +    resize: resize || 'vertical',
Исправил

2023-02-20 09:16 UTC, Krezo commented on packages/client/src/components/textarea/textarea.tsx
> +  const textateaStyle = {
Исправил

2023-02-20 09:17 UTC, antonbezushko commented on packages/client/src/components/textarea/textarea.tsx
> +  const isValid = !!errorText;
Изменил тип для пропса валидации

2023-02-20 09:17 UTC, Krezo commented on packages/client/src/components/textarea/textarea.tsx
> +        placeholder={(solo && label) || ''}
Да, label если нету фокуса как placeholder, при фокусе как label

2023-02-20 09:18 UTC, Krezo commented on packages/client/src/components/textarea/textarea.module.scss
> +      color: $text-error !important;
Да

2023-02-20 09:18 UTC, Krezo commented on packages/client/src/components/textarea/textarea.module.scss
> +      color: $text-error !important;
Нужен

2023-02-20 17:19 UTC, kate-lozovaya commented on packages/client/src/components/textarea/textarea.module.scss
> +      color: $text-error !important;
Почему нельзя без него?

2023-02-20 17:23 UTC, kate-lozovaya requested changes
Смотрю изменения после ревью, и там только миксин,  правок нет
<img width="806" alt="image" src="https://user-images.githubusercontent.com/25737137/220168878-cfb4800c-517e-444d-8c29-0b080c92d556.png">

2023-02-21 08:02 UTC, Krezo commented
> Смотрю изменения после ревью, и там только миксин, правок нет <img alt="image" width="806" src="https://user-images.githubusercontent.com/25737137/220168878-cfb4800c-517e-444d-8c29-0b080c92d556.png">

И правда, правки не залились. Обновляю

2023-02-21 09:10 UTC, kate-lozovaya commented on packages/client/src/components/textarea/textarea.tsx
> +    }
с этим не согласен?

2023-02-21 09:19 UTC, kate-lozovaya commented on packages/client/src/components/textarea/textarea.module.scss
> +  background: #fff;
Тут не ответил

2023-02-21 09:21 UTC, kate-lozovaya reviewed
Не ответил на два вопроса в ревью

2023-02-21 10:32 UTC, Krezo commented on packages/client/src/components/textarea/textarea.module.scss
> +  background: #fff;
да, есть

2023-02-21 10:34 UTC, Krezo commented on packages/client/src/components/textarea/textarea.module.scss
> +  background: #fff;
Для белого отдельного цвета нет, а выносить в глобальные переменные цвета для компонента, когда используется модули не вижу смысла, т.е он нигде больше использоваться не будет.

2023-02-21 18:05 UTC, kate-lozovaya commented on packages/client/src/components/textarea/textarea.module.scss
> +  background: #fff;
Должна быть единообразность оформления, потому что может возникнуть новый дизайн, новая страничка, где этот белый цвет понадобится

2023-02-21 18:09 UTC, kate-lozovaya approved these changes
Не закрывай комментарии сам, пожалуйста. 
Удобнее, когда ревьювер сам кликает на свои resolve conversation, так проще проверять правки по ревью

2023-02-22 15:53 UTC, merged