Feature/mon 54 input component
22-reactors/monopoly pull request #16
Opened 2023-02-12 19:16 UTC by Krezo

### Реализация компонента Input

Задача: https://linear.app/monopoly/issue/MON-54/sverstat-komponent-input

2023-02-12 19:21 UTC, Krezo commented
На конфлиты прошу внимания не обращать. Разрешу, когда зальют в dev фиксы билда проекта

2023-02-15 23:48 UTC, skaamoogs requested changes
В целом все хорошо. В сервере только убери изменения.

2023-02-15 23:48 UTC, skaamoogs commented on packages/client/src/components/input/input.tsx
> +      {showPassword && (
Получается если showPassword true, то иконка всегда будет показываться, даже если тип инпута не password. Хотя это наверное не критично, если мы правильно будем использовать компонент. Но я бы добавил проверку, что тип password.

2023-02-15 23:48 UTC, skaamoogs commented on packages/server/index.ts
> +// import { createClientAndConnect } from './db';
В сервере пока ничего не делали, поэтому здесь лучше ничего не менять. При запуске сервера есть ошибка, но она изначально была.

2023-02-16 09:33 UTC, Krezo commented on packages/client/src/components/input/input.tsx
> +      {showPassword && (
Да, думаю это не критично

2023-02-16 09:34 UTC, Krezo commented on packages/server/index.ts
> +// import { createClientAndConnect } from './db';
vercel же не билдится без комментов

2023-02-16 09:41 UTC, skaamoogs approved these changes

2023-02-16 20:15 UTC, kate-lozovaya requested changes
input выглядит копией textarea. Может подумать над их объединением?

2023-02-16 20:15 UTC, kate-lozovaya commented on packages/client/src/types/validation.ts
> +export interface IValidationInputProps {
[Вопрос]
Уже писала его в другом PR про textarea, продублирую. Не знаю, кто автор строки.

Почему переменная может быть и string, и boolean, и undefined?
Не подойдет ли значение undefined как альтернатива для boolean?

2023-02-16 20:15 UTC, kate-lozovaya commented on packages/client/src/components/input/input.tsx
> +  const isValid = !!errorText;
[Предложение]
Уже писала его в другом PR про textarea, продублирую. Не знаю, кто автор строки.

!!undefined = false, можно оставить только тип string для интерфейса IValidationInputProps?: string

2023-02-16 20:15 UTC, kate-lozovaya commented on packages/client/src/components/input/input.tsx
> +        type={showPasswordComputed ? 'text' : type || 'text'}
[Исправление]
type проверяешь на `undefined`, лучше использовать `??`
И условие содержит подусловие. лучше вынести в переменную
`const inputType = showPasswordComputed ? 'text' : type ?? 'text'`

2023-02-20 09:05 UTC, Krezo commented
> input выглядит копией textarea. Может подумать над их объединением?

У textarea есть доп. параметры, которые не хочется мешаться в input и усложнять логику

2023-02-20 09:07 UTC, Krezo commented on packages/client/src/types/validation.ts
> +export interface IValidationInputProps {
Это для данных от валидатора, если строка, то будет текст ошибки или булево значение (вообще только false или строка с текстом ошибки)

2023-02-20 09:11 UTC, Krezo commented on packages/client/src/types/validation.ts
> +export interface IValidationInputProps {
Поправил на string | undefined

2023-02-20 09:12 UTC, Krezo commented on packages/client/src/components/input/input.tsx
> +        type={showPasswordComputed ? 'text' : type || 'text'}
Исправил

2023-02-20 22:01 UTC, kate-lozovaya approved these changes
В вашем проекте я не могу делать resolve conversation (
[В доке](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/commenting-on-a-pull-request#resolving-conversations) пишут про права на запись. Можете глянуть и дать мне их?

2023-02-21 08:06 UTC, Krezo commented
> В вашем проекте я не могу делать resolve conversation ( [В доке](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/commenting-on-a-pull-request#resolving-conversations) пишут про права на запись. Можете глянуть и дать мне их?

Права должны были дать

2023-02-21 08:57 UTC, kate-lozovaya approved these changes
Да, права теперь есть, спасибо!

2023-02-21 10:23 UTC, merged