Feature/mon 55 select component
22-reactors/monopoly pull request #17
Opened 2023-02-12 22:58 UTC by Krezo

### Реализация компонента select

Задача: https://linear.app/monopoly/issue/MON-55/sverstat-komponent-select

2023-02-16 12:04 UTC, skaamoogs requested changes

2023-02-16 12:04 UTC, skaamoogs commented on packages/client/src/components/select/select.module.scss
> +  border-color: $text-error !important;
Вроду уже писали про important. Пожалуйста, не используй его

2023-02-16 12:04 UTC, skaamoogs commented on packages/client/src/components/select/selectOption.tsx
> +  value: string;
Не совсем понятно для чего label и value. Нельзя одним чем-то обойтись?

2023-02-16 12:04 UTC, skaamoogs commented on packages/client/src/components/select/selectOption.tsx
> +  data?: T;
Для чего свойство data? Не нашел где оно используется?

2023-02-16 12:04 UTC, skaamoogs commented on packages/client/src/main.tsx
> +    <Test />
Из main нужно убрать правки

2023-02-20 09:00 UTC, Krezo commented on packages/client/src/components/select/selectOption.tsx
> +  data?: T;
Чтобы была возможность добавить. доп. параметры

2023-02-20 09:01 UTC, Krezo commented on packages/client/src/components/select/selectOption.tsx
> +  value: string;
Точто также как работает обычный select. Одно поле для вывода текста, другое которое испоользуется в запросе

2023-02-20 09:01 UTC, Krezo commented on packages/client/src/components/select/select.module.scss
> +  border-color: $text-error !important;
Тут не обойтись без него

2023-02-20 09:03 UTC, Krezo commented on packages/client/src/components/select/select.module.scss
> +  border-color: $text-error !important;
потом отрефакторим

2023-02-20 21:23 UTC, kate-lozovaya commented
PR заблочен. Попроси коллегу посмотреть правки по ревью, пожалуйста

2023-02-20 21:35 UTC, kate-lozovaya commented
Можешь скинуть скрин, что получилось

2023-02-20 21:54 UTC, kate-lozovaya requested changes
А почему не использован [стандартный тег select](https://doka.guide/html/select/)?

2023-02-20 21:54 UTC, kate-lozovaya commented on packages/client/src/components/select/select.module.scss
> +  border-color: $text-error !important;
Согласна, что надо убрать )
Их надо убрать везде, потому что не может не применяться border-color, если все написано без important. Но мне ок, если это будет сделано позже.
Если ссылаешься на рефакторинг, стоит создать задачу и написать TODO в коде с ее номером

2023-02-20 21:54 UTC, kate-lozovaya commented on packages/client/src/components/select/select.module.scss
> +  border-color: $text-additional;
[Предложение]
Можно объединить `border-bottom: 1px solid $text-additional;`

2023-02-20 21:54 UTC, kate-lozovaya commented on packages/client/src/types/validation.ts
> +  errorText?: string | boolean;
[Предложение]
Точно уже где-то писала, что можно использовать тип для errorText без `boolean`.
`errorText?: string;`

2023-02-20 21:54 UTC, kate-lozovaya commented on packages/client/src/components/select/select.tsx
> +    options?.find(o => o.value === value?.value) || defaultOption
[Исправление]
Идет проверка на `undefined`, лучше использовать ?? вместо ||

2023-02-20 21:54 UTC, kate-lozovaya commented on packages/client/src/components/select/select.tsx
> +        value={selectedOption?.label}
[Исправление]
В строках 25-27 есть дефолтное значение, то есть `selectedOption` никогда не будет `undefined`, вопросительный знак не нужен

2023-02-20 21:54 UTC, kate-lozovaya commented on packages/client/src/components/select/select.tsx
> +  const isValid = !!errorText;
[Вопрос]
Тут опечатка? Если есть errorText, то форма же будет невалидной. Поправь, если не так

2023-02-20 21:54 UTC, kate-lozovaya commented on packages/client/src/components/select/select.tsx
> +      </svg>
[Исправление]
svg не нужно вставлять прямо в компонент, ее стоит вынести. Ведь если дизайнер внесет изменения в картинку, должен поменяться только файл с картинкой, а трогать компонент не нужно

2023-02-20 21:54 UTC, kate-lozovaya commented on packages/client/src/components/select/select.tsx
> +        className={style.select}></input>
[Предложение]
Будешь что-то править, перенеси </input> на новую строку, и проверь настройки претира, чтобы исправление было автоматическим

2023-02-20 21:54 UTC, kate-lozovaya commented on packages/client/src/components/select/select.module.scss
> +  transition: all $animation-time;
[Предложение]
[`transition` стоит писать](https://doka.guide/a11y/prefers-reduced-motion/) в `@media (prefers-reduced-motion: no-preference)`, чтобы анимация не включалась, если пользователь ее принудительно выключил

2023-02-20 21:54 UTC, kate-lozovaya commented on packages/client/src/components/select/select.module.scss
> +  max-height: 320px;
[Предложение]
Если интересно, можно сделать красивый скролл бар, чтобы некрасивый стандартный не портил вид

2023-02-20 21:54 UTC, kate-lozovaya commented on packages/client/src/components/select/selectOption.module.scss
> +  &:hover {
[Предложение]
Лучше ховер обернуть в `@media (hover: hover) and (poiner: fine)`, чтобы только на экранах с мышкой наведение было

2023-02-21 07:25 UTC, Krezo commented on packages/client/src/components/select/select.module.scss
> +  max-height: 320px;
Предложу команде, как закончим основную работу

2023-02-21 07:26 UTC, Krezo commented on packages/client/src/components/select/select.tsx
> +        className={style.select}></input>
Сделал самозакрывающийся input тег

2023-02-21 07:31 UTC, Krezo commented on packages/client/src/components/select/select.tsx
> +      </svg>
Вынес в отдельный компонент

2023-02-21 07:32 UTC, Krezo commented on packages/client/src/components/select/select.tsx
> +  const isValid = !!errorText;
Нет, все верно

2023-02-21 07:33 UTC, Krezo commented on packages/client/src/components/select/select.tsx
> +    options?.find(o => o.value === value?.value) || defaultOption
Исправил

2023-02-21 07:34 UTC, Krezo commented on packages/client/src/components/select/select.tsx
> +        value={selectedOption?.label}
Исправил

2023-02-21 07:34 UTC, Krezo commented on packages/client/src/types/validation.ts
> +  errorText?: string | boolean;
Исправил

2023-02-21 07:36 UTC, Krezo commented
> А почему не использован [стандартный тег select](https://doka.guide/html/select/)?

По макету не подходит

2023-02-21 07:42 UTC, Krezo commented on packages/client/src/components/select/select.module.scss
> +  border-color: $text-error !important;
Избавился от important

2023-02-21 08:53 UTC, kate-lozovaya commented
> > А почему не использован [стандартный тег select](https://doka.guide/html/select/)?
> 
> По макету не подходит

А покажи макет и скрины, пожалуйста

2023-02-21 09:02 UTC, kate-lozovaya commented on packages/client/src/components/select/select.module.scss
> +  transition: all $animation-time;
Это решил не делать? Если да, напиши это сюда в коммент

2023-02-21 09:05 UTC, kate-lozovaya commented on packages/client/src/components/select/selectOption.module.scss
> +  &:hover {
не увидела этот медиа запрос

2023-02-21 10:31 UTC, Krezo commented
> > > А почему не использован [стандартный тег select](https://doka.guide/html/select/)?
> > 
> > 
> > По макету не подходит
> 
> А покажи макет и скрины, пожалуйста

Макет
![image](https://user-images.githubusercontent.com/19520555/220319400-47d4d247-e73b-4296-95a5-3b99255b91b4.png)

Верстка
![image](https://user-images.githubusercontent.com/19520555/220320149-a7c8d760-2210-4e8a-a654-ea8d49fcb5fc.png)

2023-02-21 18:28 UTC, kate-lozovaya requested changes
Не сделал медиа запросы для `:hover` и `transition` и ничего не написал в комменты про них. 
Не понимаю, что это значит: 
- комменты не увидел
- с комментами не согласен

Ответь, пожалуйста

2023-02-22 16:02 UTC, Krezo commented on packages/client/src/components/select/selectOption.module.scss
> +  &:hover {
В медазапросы нельзя встраивать @extend + условие (poiner: fine) на моем ноутбуке с мышкой не работает

2023-02-22 16:02 UTC, antonbezushko commented
> packages/client/src/components/select/selectOption.module.scss

> Не сделал медиа запросы для `:hover` и `transition` и ничего не написал в комменты про них. Не понимаю, что это значит:
> 
> * комменты не увидел
> * с комментами не согласен
> 
> Ответь, пожалуйста

Ответил https://github.com/22-reactors/monopoly/pull/17#discussion_r1114558840

2023-02-23 07:35 UTC, kate-lozovaya approved these changes

2023-02-23 09:54 UTC, merged