Feature/mon 40 login and registration view
22-reactors/monopoly pull request #2
Opened 2023-02-04 14:49 UTC by Renovacio3429

Верстка страниц логина и регистрации

2023-02-05 06:30 UTC, nullorone commented on packages/client/src/components/backgroundtheme/loginbackgroundtheme/LoginBackGroundTheme.tsx
> +import styles from './loginBackGroundTheme.module.scss'
лучше импортировать в единственном числе, потому что ты импортируешь 1 стилевой файл.
То есть здесь и в других местах просто `style`

2023-02-05 06:30 UTC, nullorone commented on packages/client/src/components/form/loginformheader/LoginFormHeader.tsx
> +            <h2>{props.headerName}</h2>
а где тут класс потерялся? В других компонентах у каждого элемента есть классы, а тут ты обошел стороной заголовок и ссылку

2023-02-05 06:30 UTC, nullorone commented on packages/client/src/components/themetoggler/ThemeToggler.tsx
> +        <div>
если тебе нужна просто обертка, то лучше использовать реакт фрагмент

2023-02-05 06:30 UTC, nullorone commented on packages/client/src/components/themetoggler/ThemeToggler.tsx
> +            <div className={`${styles.formContainer} ${themeStyle}`}>
добавь либу classnames. Она позволяет объединять классы и использовать логику для добавления классов.

2023-02-05 06:30 UTC, nullorone commented on packages/client/src/components/themetoggler/themeToggler.module.scss
> +.formContainerLightTheme input {
ты добавляешь в стилизацию логику. Такое надо разруливать на уровне пропсов у компонента. Передаешь пропсу и уже в компоненте меняется цвет у нужного элемента

2023-02-05 06:30 UTC, nullorone commented on packages/client/src/index.scss
> +  src: url('times.ttf');
а зачем этот шрифт нам?

2023-02-05 06:30 UTC, nullorone commented on packages/client/src/index.scss
> +body, h2 {
если мы обнуляем у  h2 отступы, то почему у параграфа не делаем также?
Лучше обнулить только у body, а у h2, h1, p уже точечно обнулять. Таким образом ты избегаешь проблем в будущем

2023-02-05 06:30 UTC, nullorone commented on packages/client/src/pages/login/login.module.scss
> +html,
это плохая практика. Ты перебиваешь дефолтные шрифты на всем документе, тем самым добавляешь переопределение во все input, button которые будут с другим шрифтом

2023-02-05 06:30 UTC, nullorone commented on packages/client/src/pages/login/login.module.scss
> +    overflow: hidden;
а это зачем?)

2023-02-05 06:30 UTC, nullorone commented on packages/client/src/pages/login/login.module.scss
> +a {
лучше не перебивать стандартные шрифты

2023-02-05 06:30 UTC, nullorone commented on packages/client/src/components/backgroundtheme/loginbackgroundtheme/LoginBackGroundTheme.tsx
> +const LoginBackGroundTheme = (props: ILoginBackGroundTheme) => {
если окажется так, что фон на логине и реги станет разным, нам придется переделывать компоненты?
Предлагаю отказаться от этого компонента, потому что он не несет за собой смысла. Либо его надо переделать с пропсой передаваемой фоновой картинки, назвать по другому, более универсально, чтобы использовать на всех страницах, но опять же, смысла в компоненте из 1 дива и стилизацией этого дива я не вижу.

2023-02-05 06:30 UTC, nullorone commented on packages/client/src/pages/register/register.module.scss
> +html,
это ведь препроцессор, можно юзать импорты без опасности подгрузки новых стилей

2023-02-05 06:30 UTC, nullorone commented on packages/client/src/pages/register/register.tsx
> +        <LoginBackGroundTheme>
как-то не сочетается login в register ^_^

2023-02-05 06:30 UTC, nullorone commented on packages/client/src/pages/register/register.tsx
> +                <LoginFormHeader
лучше назвать компонент универсально

2023-02-05 06:30 UTC, nullorone commented on packages/client/src/pages/register/register.tsx
> +                <LoginForm submitBtnName="Войти">
мне кажется и loginFormHeader и LoginForm можно объединить в одну форму и пробрасывать пропсы, например,
``` {
login: {
  header: "Вход в игру",
 hrefName: "создать аккаунт"
},
registration: {
  fields: [
    {
      fieldId: ....
    }
  ]
}
}
```

2023-02-05 06:30 UTC, nullorone commented on packages/client/src/pages/register/register.tsx
> +                        key="1" />
очень сильная декомпозиция. Достаточно в пропсах передать массив с данными инпутов, а в самой форме уже маппать их и возвращать компоненты, не забывая указывать key

2023-02-05 07:58 UTC, Renovacio3429 commented on packages/client/src/index.scss
> +  src: url('times.ttf');
В макете такой-же)

2023-02-05 08:00 UTC, Renovacio3429 commented on packages/client/src/index.scss
> +body, h2 {
я обнулял отступы только у тех элементов, которые сам использовал, про параграф даже и не подумал т.к. его не использовал нигде)

2023-02-05 08:15 UTC, Renovacio3429 commented on packages/client/src/pages/login/login.module.scss
> +    overflow: hidden;
Если ты пользуешь тачпадом (на мышке мб по-другому), то можно выйти за пределы фонового изображения, а там все белое, мне это показалось некрасивым)

2023-02-05 16:26 UTC, Renovacio3429 commented on packages/client/src/index.scss
> +  src: url('times.ttf');
Убрал, просто на макете был такой

2023-02-05 16:28 UTC, Renovacio3429 commented on packages/client/src/pages/login/login.module.scss
> +    overflow: hidden;
Пока оставил, не думаю что это кому-то будет мешать

2023-02-05 16:30 UTC, Renovacio3429 commented on packages/client/src/pages/login/login.module.scss
> +a {
У меня матрица 13 дюймов, слова плохо читаются

2023-02-05 16:30 UTC, Renovacio3429 commented on packages/client/src/pages/login/login.module.scss
> +a {
Убрал шрифты. А как тогда правильно делать?

2023-02-05 16:31 UTC, Renovacio3429 commented on packages/client/src/pages/register/register.module.scss
> +html,
Ничего не понял, но на всякий случай убрал)

2023-02-05 16:36 UTC, Renovacio3429 commented
В данный момент у страницы логина и страницы регистрации одинаковый код, решил сделать так, что бы в будущем можно было кастомизировать отдельно, если это потребуется

2023-02-06 01:46 UTC, nullorone commented on packages/client/package.json
> +    "classnames": "^2.3.2"
необходимо фиксировать версии, т.е. когда добавляет пакет указывать флаг -E, Пример, npm add -DE classnames
(флаг D добавляет в dev зависимости, а E фиксирует версию)

2023-02-06 01:48 UTC, nullorone commented on packages/client/src/components/fieldset/inputfieldset/InputFieldSet.module.scss
> +  color: black !important;
ай яй яй, не используй импортант
Допускается его использовать только когда работаешь с бутстрапом и прочими либами и у тебя безвыходная ситуация, что надо перебить вес селектора либы.

2023-02-06 02:01 UTC, nullorone commented on packages/client/src/components/fieldset/inputfieldset/InputFieldSet.tsx
>  export type InputTypeEnum = 'text' | 'password'
с неймингом проблема. У тебя здесь просто тип, а не енам

2023-02-06 02:01 UTC, nullorone commented on packages/client/src/components/fieldset/inputfieldset/InputFieldSet.tsx
> +        [props.isLightTheme ? style.labelLightTheme : style.labelDarkTheme])
вроде можно и без квадратных скобок

2023-02-06 02:09 UTC, nullorone commented on packages/client/src/components/header/header.tsx
> +        [props.className ? props.className : ''],
можно просто props.className, если будет undefined, то classNames ничего не добавит и ошибку не выкинет. Обработает этот кейс

2023-02-06 02:10 UTC, nullorone commented on packages/client/src/components/link/link.module.scss
> +    color: white !important;
не используй импортанты

2023-02-06 02:10 UTC, nullorone commented on packages/client/src/components/link/link.tsx
> +import style from "./link.module.scss"
зачем выделять элемент в компонент?

2023-02-06 02:12 UTC, nullorone commented on packages/client/src/components/themetoggler/ThemeToggler.tsx
> +                <button onClick={toggleTheme} className={iconBtnClass}></button>
icon вводит в заблужениt в названии. У тебя ведь кнопка, тогда просто btn, или можно toggleBtn

2023-02-06 02:13 UTC, nullorone commented on packages/client/src/index.scss
> +  font-family: 'Times New Roman', Times, serif
не могу понять, что за шрифт Times? Это какой-то стандартный?

2023-02-06 02:16 UTC, nullorone commented on packages/client/src/pages/login/login.tsx
> +        return <InputFieldSet key={i}
можно сократить до такой записи и не описывать каждую передаваемую пропсу

```
return <InputFieldSet key={i} {...inputProp} />
```

2023-02-06 02:19 UTC, nullorone commented on packages/client/src/pages/login/login.tsx
> +                <LoginAndRegistrForm
<LoginAndRegistrForm {...props.loginProps}>{inputItems}</LoginAndRegistrForm>

2023-02-06 02:20 UTC, nullorone commented on packages/client/src/pages/login/login.tsx
> +    const loginInputsProps = loginFormProps.inputsProps;
лишние сохранения в константы. Можно сделать деструктуризацию для удобства обращения

```
const {loginProps: { inputsProps }} = props;
```

2023-02-06 02:22 UTC, nullorone commented on packages/client/src/pages/login/login.tsx
> +    loginProps: ILoginForm
почему нельзя использовать интерфейс ILoginForm сразу?
Можно переименовать в ILoginPage и сойдет

2023-02-06 02:22 UTC, nullorone commented on packages/client/src/pages/login/loginProps.tsx
> +    headerLevel: 'h2',
можешь пояснить, зачем эта пропса?

2023-02-06 02:24 UTC, nullorone commented on packages/client/src/components/form/loginandregistrform/loginAndRegistrForm.tsx
> +}
не хватает пропсы-экшена для формы

2023-02-06 02:25 UTC, nullorone commented on packages/client/src/components/form/loginandregistrform/loginAndRegistrForm.tsx
> +    headerLevel: React.ElementType
ты же передаешь в пропсу 'h2' строку, а указываешь, что элемент?

2023-02-06 02:26 UTC, nullorone commented on packages/client/src/pages/register/register.tsx
> +
по этому файлу аналогичные комменты, как из логина

2023-02-06 02:27 UTC, nullorone commented on packages/client/src/pages/register/register.module.scss
> +.registrBackground {
может класс назвать bg или background и просто переиспользовать(импортировать) стили из логина или наоборот из регистра в логин? Не нужный копипастинг

2023-02-06 05:30 UTC, nullorone commented on packages/client/src/pages/register/register.module.scss
> +html,
https://sass-lang.com/documentation/at-rules/import

2023-02-06 09:02 UTC, Renovacio3429 commented on packages/client/src/pages/login/login.tsx
> +        return <InputFieldSet key={i}
Вау, не знал что так можно

2023-02-06 09:08 UTC, Renovacio3429 commented
Касательно _"ты же передаешь в пропсу 'h2' строку, а указываешь, что элемент?"_
Так делать можно, к примеру если я напишу 'h100' typescript подвесит мне эту строку как ошибку.
Например я ввел headerLevel: 'h100' и вижу ошибку:

(property) IRegistrForm.headerLevel: React.ElementType<any>
Type '"h100"' is not assignable to type 'ElementType<any>'.ts(2322)
register.tsx(15, 5): The expected type comes from property 'headerLevel' which is declared here on type 'IRegistrForm'

_"можешь пояснить, зачем эта пропса?"_ 
(речь опять про h2 в пропсах), мы можешь регулить уровнем заголовка из пропсов
указать h1 или h2 например

2023-02-06 09:17 UTC, nullorone commented
> Касательно _"ты же передаешь в пропсу 'h2' строку, а указываешь, что элемент?"_ Так делать можно, к примеру если я напишу 'h100' typescript подвесит мне эту строку как ошибку. Например я ввел headerLevel: 'h100' и вижу ошибку:
> 
> (property) IRegistrForm.headerLevel: React.ElementType Type '"h100"' is not assignable to type 'ElementType'.ts(2322) register.tsx(15, 5): The expected type comes from property 'headerLevel' which is declared here on type 'IRegistrForm'
> 
> _"можешь пояснить, зачем эта пропса?"_ (речь опять про h2 в пропсах), мы можешь регулить уровнем заголовка из пропсов указать h1 или h2 например

зачем нам такая возможность?)

2023-02-06 09:26 UTC, Renovacio3429 commented
Выше ты указывал на проблему: 

_const LoginFormHeader = (props: ILoginFormHeader) => {
    return (
        <div className={styles.headerFormContainer}>
            <h2>{props.headerName}</h2>
 
Member
@[nullorone](https://github.com/nullorone) nullorone [yesterday](https://github.com/22-reactors/monopoly/pull/2#discussion_r1096614095)
а где тут класс потерялся? В других компонентах у каждого элемента есть классы, а тут ты обошел стороной заголовок и ссылку_

Я подумал, что нужно заголовок нужно вынести в отдельный компонент и дать пользователю выставить такой размер какой ему нужно одно строчкой, может быть я не правильно понял замечание?

2023-02-06 10:01 UTC, Renovacio3429 commented
> > Касательно _"ты же передаешь в пропсу 'h2' строку, а указываешь, что элемент?"_ Так делать можно, к примеру если я напишу 'h100' typescript подвесит мне эту строку как ошибку. Например я ввел headerLevel: 'h100' и вижу ошибку:
> > (property) IRegistrForm.headerLevel: React.ElementType Type '"h100"' is not assignable to type 'ElementType'.ts(2322) register.tsx(15, 5): The expected type comes from property 'headerLevel' which is declared here on type 'IRegistrForm'
> > _"можешь пояснить, зачем эта пропса?"_ (речь опять про h2 в пропсах), мы можешь регулить уровнем заголовка из пропсов указать h1 или h2 например
> 
> зачем нам такая возможность?)

Выше ты указывал на проблему:

const LoginFormHeader = (props: ILoginFormHeader) => {
return (
<div className={styles.headerFormContainer}>
<h2>{props.headerName}</h2>

Member
@[nullorone](https://github.com/nullorone) nullorone https://github.com/22-reactors/monopoly/pull/2#discussion_r1096614095
а где тут класс потерялся? В других компонентах у каждого элемента есть классы, а тут ты обошел стороной заголовок и ссылку

Я подумал, что нужно заголовок нужно вынести в отдельный компонент и дать пользователю выставить такой размер какой ему нужно одно строчкой, может быть я не правильно понял замечание? Иначе зачем выносить в отдельный класс заголовок?

2023-02-06 10:09 UTC, nullorone commented
> > > Касательно _"ты же передаешь в пропсу 'h2' строку, а указываешь, что элемент?"_ Так делать можно, к примеру если я напишу 'h100' typescript подвесит мне эту строку как ошибку. Например я ввел headerLevel: 'h100' и вижу ошибку:
> > > (property) IRegistrForm.headerLevel: React.ElementType Type '"h100"' is not assignable to type 'ElementType'.ts(2322) register.tsx(15, 5): The expected type comes from property 'headerLevel' which is declared here on type 'IRegistrForm'
> > > _"можешь пояснить, зачем эта пропса?"_ (речь опять про h2 в пропсах), мы можешь регулить уровнем заголовка из пропсов указать h1 или h2 например
> > 
> > 
> > зачем нам такая возможность?)
> 
> Выше ты указывал на проблему:
> 
> const LoginFormHeader = (props: ILoginFormHeader) => { return ( <div className={styles.headerFormContainer}> <h2>{props.headerName}</h2>
> 
> Member @[nullorone](https://github.com/nullorone) nullorone [#2 (comment)](https://github.com/22-reactors/monopoly/pull/2#discussion_r1096614095) а где тут класс потерялся? В других компонентах у каждого элемента есть классы, а тут ты обошел стороной заголовок и ссылку
> 
> Я подумал, что нужно заголовок нужно вынести в отдельный компонент и дать пользователю выставить такой размер какой ему нужно одно строчкой, может быть я не правильно понял замечание? Иначе зачем выносить в отдельный класс заголовок?

я имел в виду стилевой class)) className =)

2023-02-06 10:29 UTC, Renovacio3429 commented
> 

Понял, принял. Поправил)

2023-02-06 10:29 UTC, Renovacio3429 commented
> > > > Касательно _"ты же передаешь в пропсу 'h2' строку, а указываешь, что элемент?"_ Так делать можно, к примеру если я напишу 'h100' typescript подвесит мне эту строку как ошибку. Например я ввел headerLevel: 'h100' и вижу ошибку:
> > > > (property) IRegistrForm.headerLevel: React.ElementType Type '"h100"' is not assignable to type 'ElementType'.ts(2322) register.tsx(15, 5): The expected type comes from property 'headerLevel' which is declared here on type 'IRegistrForm'
> > > > _"можешь пояснить, зачем эта пропса?"_ (речь опять про h2 в пропсах), мы можешь регулить уровнем заголовка из пропсов указать h1 или h2 например
> > > 
> > > 
> > > зачем нам такая возможность?)
> > 
> > 
> > Выше ты указывал на проблему:
> > const LoginFormHeader = (props: ILoginFormHeader) => { return (  ## {props.headerName}
> > Member @[nullorone](https://github.com/nullorone) nullorone [#2 (comment)](https://github.com/22-reactors/monopoly/pull/2#discussion_r1096614095) а где тут класс потерялся? В других компонентах у каждого элемента есть классы, а тут ты обошел стороной заголовок и ссылку
> > Я подумал, что нужно заголовок нужно вынести в отдельный компонент и дать пользователю выставить такой размер какой ему нужно одно строчкой, может быть я не правильно понял замечание? Иначе зачем выносить в отдельный класс заголовок?
> 
> я имел в виду стилевой class)) className =)

Понял, принял. Поправил)

2023-02-07 07:55 UTC, nullorone approved these changes

2023-02-07 15:34 UTC, kate-lozovaya commented on packages/client/src/components/fieldset/inputfieldset/InputFieldSet.tsx
> +    return (
[Предложение]
Я видела что-то похожее в другом [PR](https://github.com/22-reactors/monopoly/pull/8). 
Тут стоит договориться и посмотреть, можете ли вы использовать один и тат же компонент

2023-02-07 15:35 UTC, kate-lozovaya commented
У ветки конфликт, смержить не получится. Можешь поправить, пожалуйста

2023-02-08 08:51 UTC, Renovacio3429 commented
![image](https://user-images.githubusercontent.com/59480386/217480211-80628ce4-366f-4479-a735-eb79badf1895.png)
![image](https://user-images.githubusercontent.com/59480386/217480388-b417cf27-70eb-4543-8c56-40190862ce26.png)
![image](https://user-images.githubusercontent.com/59480386/217480481-984f2896-0b86-4b92-bc66-1f37894fd9c9.png)
![image](https://user-images.githubusercontent.com/59480386/217480728-5e4f0abc-ad63-4d78-b678-54987cf627fd.png)

2023-02-08 16:19 UTC, Renovacio3429 commented on packages/client/src/components/fieldset/inputfieldset/InputFieldSet.tsx
> +    return (
я думаю, что после верстки всех страниц  можно будет провести небольшой рефакторинг. Вот, например, сейчас я хочу в другой задаче использовать компонент из этой задачи (смена темы), но при этом этот, я все никак не могу закрыть этот пул реквест, а время идет и идет)

2023-02-08 17:26 UTC, kate-lozovaya commented
У тебя видны изменения, которые делал другой человек вот в этом [PR](https://github.com/22-reactors/monopoly/pull/8). Лучше пользоваться командой rebase. [Вот тут на хабре](https://habr.com/ru/post/161009/) есть рисунки с комитами. Лучше использовать его вместо merge для решения конфликта в ветках.

В PR должны быть только твои изменения, которые касаются твоей задачи, чтобы в будущем можно было посмотреть историю и ревьюер не страдал) 
Если есть чьи-то еще, значит что-то пошло не так. Давай в следующий раз не делать merge. И было бы здорово передать это всей команде.

2023-02-08 17:32 UTC, kate-lozovaya commented
Папки avatar, button и info можно не смотреть, они из другого PR, верно?

2023-02-08 17:37 UTC, kate-lozovaya commented on packages/client/src/components/fieldset/inputfieldset/InputFieldSet.tsx
> +    return (
[Предложение]
Я видела PR двоих людей с компонентами, у вас вышли разные стили. У тебя `export default ComponentName`, а у твоего коллеги `export function ComponentName`.
Перед рефакторингом лучше договориться, в каком вы стиле пишете, и сделать все компоненты одинаковыми

2023-02-08 18:28 UTC, kate-lozovaya requested changes

2023-02-08 18:28 UTC, kate-lozovaya commented on packages/client/src/components/fieldset/inputfieldset/InputFieldSet.tsx
> +                placeholder=" " />
[Вопрос]
Точно ли тут нужен именно пробел для `placeholder`?

2023-02-08 18:28 UTC, kate-lozovaya commented on packages/client/src/components/fieldset/inputfieldset/InputFieldSet.module.scss
> +  border: none;
[Предложение]
Класс `fieldset` используешь для компонента `fieldset`. И в обоих селекторах есть свойство `border: none;`. Можно убрать для класса, чтобы не было дублирования

2023-02-08 18:28 UTC, kate-lozovaya commented on packages/client/src/components/fieldset/inputfieldset/InputFieldSet.module.scss
> +  transition: background-color 600000s 0s, color 600000s 0s;
[Исправление]
Хорошей практикой является использование transition в `@media (prefers-reduced-motion: no-preference)`, чтобы анимация была только у тех пользователей, у которых она не отключена
[Вот тут](https://doka.guide/a11y/prefers-reduced-motion/) можно посмотреть, что это за медиа запрос такой

2023-02-08 18:28 UTC, kate-lozovaya commented on packages/client/src/components/fieldset/inputfieldset/InputFieldSet.module.scss
> +  transition: 0.3s;
[Исправление]
Выше написала, что лучше использовать `@media (prefers-reduced-motion: no-preference)` для  transition

2023-02-08 18:28 UTC, kate-lozovaya commented on packages/client/src/components/form/loginandregistrform/loginAndRegistrForm.module.scss
> +  color: white;
[Предложение]
Много где используются цвета `white` и `black`. Лучше вынести их в переменные, чтобы когда дизайнер примет решение поменять `black` на `#242424`, можно это было сделать всего одной строчкой

2023-02-08 18:28 UTC, kate-lozovaya commented on packages/client/src/components/themetoggler/ThemeToggler.tsx
> +    const toggleBtn = classNames(style.themeTogglerBtn,
[Исправление]
В файле `loginAndRegistrForm.tsx` и в этом файле на 21 строчке для переменных использовалось слово Class в названии. Лучше сохранить консистентность и назвать переменную `toggleBtnClass`.

2023-02-08 18:28 UTC, kate-lozovaya commented on packages/client/src/pages/login/login.tsx
> +    inputsProps: ILoginInput[]
[Вопрос]
А почему тут не используешь `IInputFieldSet`? 
Получается, что сейчас в 3 разных файлах почти идентичные интерфейсы. Точно ли нужно это дублирование?
Если они всегда будут похожими, то придется поддерживать их актуальными в трех разных местах. 

[Предложение]
В учебном проекте можно держать модель возле компонента, к которому она относится. Тут это InputFieldSet. Я бы оставила интерфейс только в нем и импортировала его в страницах

2023-02-08 18:28 UTC, kate-lozovaya commented on packages/client/src/pages/register/register.tsx
> +    inputsProps: IRegistrInput[]
[Предложение]
Тут, как и для формы `login` импортировала бы `IInputFieldSet`

2023-02-08 18:28 UTC, kate-lozovaya commented on packages/client/src/pages/login/loginProps.tsx
> +export default LoginProps;
[Исправление]
Этому файлу нужно расширение ts.
B лучше унести его в папку mocs, которая уже есть в проекте

2023-02-08 18:28 UTC, kate-lozovaya commented on packages/client/src/pages/register/registrProps.tsx
> +export default RegistrProps;
[Исправление]
Этому файлу нужно расширение ts.
B лучше унести его в папку mocs, которая уже есть в проекте

2023-02-09 09:19 UTC, Renovacio3429 commented
> Папки avatar, button и info можно не смотреть, они из другого PR, верно?

Все верно)

2023-02-09 09:22 UTC, Renovacio3429 commented on packages/client/src/components/fieldset/inputfieldset/InputFieldSet.tsx
> +                placeholder=" " />
Иначе анимация не работает, то есть когда пользователь нажимает на input, label "уезжает" наверх, сильно ли плохо так реализовывать анимацию? Как сделать лучше не знаю(

2023-02-09 09:28 UTC, Renovacio3429 commented
Теперь Deployment has failed ошибка)))) Я перестаю понимать, что мне нужно сделать, что бы сдать верстку 2 страниц. Cчитаю этот пул-реквест сильно потерей времени, все-такие это учебный проект и нам дают очень мало времени (2 недели на все страницы и помимо верстки еще задачи), стоит ли так глубоко разбирать верстку страниц? Если бы не сроки, я бы не писал подобного сообщения. Простите, пригорело(

2023-02-09 09:38 UTC, kate-lozovaya commented on packages/client/src/components/fieldset/inputfieldset/InputFieldSet.tsx
> +                placeholder=" " />
А можешь видео показать

2023-02-09 09:43 UTC, nullorone commented
> Теперь Deployment has failed ошибка)))) Я перестаю понимать, что мне нужно сделать, что бы сдать верстку 2 страниц. Cчитаю этот пул-реквест сильно потерей времени, все-таки это учебный проект и нам дают очень мало времени (2 недели на все страницы и помимо верстки еще задачи), стоит ли так глубоко разбирать верстку страниц? Если бы не сроки, я бы не писал подобного сообщения, наоборот было бы круто разобрать все ошибки по максимуму. Простите, пригорело(

а тебе видны ошибки когда переходишь в детали с ошибкой?
<img width="1260" alt="image" src="https://user-images.githubusercontent.com/35527172/217776281-f0fbc1bd-02e1-4654-870c-dbb6f9556a15.png">

2023-02-09 09:43 UTC, Renovacio3429 commented
> У тебя видны изменения, которые делал другой человек вот в этом [PR](https://github.com/22-reactors/monopoly/pull/8). Лучше пользоваться командой rebase. [Вот тут на хабре](https://habr.com/ru/post/161009/) есть рисунки с комитами. Лучше использовать его вместо merge для решения конфликта в ветках.
> 
> В PR должны быть только твои изменения, которые касаются твоей задачи, чтобы в будущем можно было посмотреть историю и ревьюер не страдал) Если есть чьи-то еще, значит что-то пошло не так. Давай в следующий раз не делать merge. И было бы здорово передать это всей команде.

git rebase interactive, так лучше не делать?

2023-02-09 09:53 UTC, kate-lozovaya commented
> git rebase interactive, так лучше не делать?

Обычно rebase не включает изменения другого человека, у тебя они почему-то подтянулись. Вообще команда верная. Может при мерже что-то пошло не так. 
Я не пользуюсь git, поэтому не знаю его специфику, и не могу подсказать, что именно могло пойти не так, к сожалению (
Старайся просто отслеживать, какие изменения коммитишь, чтобы в PR отправлялись только твои изменения. 
Если используешь VSCode, то там в разделе Source Control можно удобно глазами посмотреть, что идет в коммит

2023-02-09 09:53 UTC, kate-lozovaya approved these changes

2023-02-09 09:53 UTC, Renovacio3429 commented
> > Теперь Deployment has failed ошибка)))) Я перестаю понимать, что мне нужно сделать, что бы сдать верстку 2 страниц. Cчитаю этот пул-реквест сильно потерей времени, все-таки это учебный проект и нам дают очень мало времени (2 недели на все страницы и помимо верстки еще задачи), стоит ли так глубоко разбирать верстку страниц? Если бы не сроки, я бы не писал подобного сообщения, наоборот было бы круто разобрать все ошибки по максимуму. Простите, пригорело(
> 
> а тебе видны ошибки когда переходишь в детали с ошибкой? <img alt="image" width="1260" src="https://user-images.githubusercontent.com/35527172/217776281-f0fbc1bd-02e1-4654-870c-dbb6f9556a15.png">

Действительно, тут я дурак получается:) Но оно почему-то запускалось и работало)

2023-02-09 10:02 UTC, merged

2023-02-09 11:11 UTC, Renovacio3429 commented on packages/client/src/components/fieldset/inputfieldset/InputFieldSet.tsx
> +                placeholder=" " />
1) Обычное состояние
![image](https://user-images.githubusercontent.com/59480386/217795999-9b502c66-c6a1-4756-baec-135e35a24093.png)
2) Пользователь нажимает на ипнут (label "уезжает" наверх)
![image](https://user-images.githubusercontent.com/59480386/217796284-0d739a1d-7b1a-4161-9e8d-c57ac1474d49.png)
3) Убираю placeholder=" " и теперь label всегда вверху
![image](https://user-images.githubusercontent.com/59480386/217796463-200a8f8c-4f43-4f49-9f2d-d8d2c7ad10d2.png)

Возможно я плохо реализовал эту анимацию через css
.fieldsetInput:focus-within ~ .fieldsetLabel,
.fieldsetInput:not(:placeholder-shown) ~ .fieldsetLabel {
  top: -20px;
  font-size: 12px;
}

скорее всего дело в placeholder-shown, а если там пусто, то правило не отрабатывает, не знаю как сделать по-другому

2023-02-09 11:12 UTC, Renovacio3429 commented on packages/client/src/components/fieldset/inputfieldset/InputFieldSet.tsx
> +                placeholder=" " />
эта стандартные css псевдо классы