Feature/mon 64 add theme card
22-reactors/monopoly pull request #21
Opened 2023-02-14 07:06 UTC by nullorone

### Добавляет компонент ThemeCard

![image](https://user-images.githubusercontent.com/35527172/218663964-48a3136c-7f72-491b-a18c-1a9668b082aa.png)

2023-02-14 08:42 UTC, Renovacio3429 approved these changes

2023-02-14 11:47 UTC, kate-lozovaya requested changes

2023-02-14 11:47 UTC, kate-lozovaya commented on packages/client/src/utils/helpers.tsx
> +export function getDeclensionWord(value: number, words: string[]): string {
[Предложение]
В массиве строк легко перепутать порядок слов, а тут он важен. Может лучше использовать объект?

2023-02-14 11:47 UTC, kate-lozovaya commented on packages/client/src/components/themeCard/themeCard.module.scss
> +  margin: 0;
[Предложение]
Можно по умолчанию в проекте убрать отступы для тегов для текста. Их ведь всегда приходится переопределять

2023-02-14 13:37 UTC, nullorone commented on packages/client/src/components/themeCard/themeCard.module.scss
> +  margin: 0;
если обнулить отступы для всех параграфов, то может быть потенциальный баг и параграф слипнется с соседним элементом. Я всегда придерживался такой позиции) Их же не просто так придумали у заголовков и параграфов) Там занимательная история связанная ещё с классической вёрсткой газет и зарождения вэба

2023-02-14 17:24 UTC, kate-lozovaya requested changes

2023-02-14 17:24 UTC, kate-lozovaya commented on packages/client/src/components/themeCard/themeCard.tsx
> +}
[Предложение]
Мапа относится к функции. Может их лучше положить в один файл? Так ее можно будет использовать и в других компонентах вместе с функцией

2023-02-15 12:09 UTC, kate-lozovaya approved these changes

2023-02-15 12:24 UTC, merged