Feature/mon 65 add theme message
22-reactors/monopoly pull request #22
Opened 2023-02-14 08:02 UTC by nullorone

###  Добавляет компонент ThemeMessage

![Uploading image.png…]()

2023-02-14 13:30 UTC, skaamoogs approved these changes
У меня замечаний нет

2023-02-14 17:44 UTC, kate-lozovaya requested changes

2023-02-14 17:44 UTC, kate-lozovaya commented on packages/client/src/components/themeMessage/themeMessage.module.scss
> +  background-size: contain;
[Вопрос]
Не часто используете эти свойства вместе? Не нужно вынести их в `mixin`?

2023-02-14 17:44 UTC, kate-lozovaya commented on packages/client/src/components/themeMessage/themeMessage.tsx
> +  const iconHandler = () => setCountLike((prevState) => prevState > 0 ? --prevState : ++prevState);
[Вопрос]
Правильно ли понимаю, что переменная `countLike` отвечает за то, поставил или снял пользователь лайк?
Может тут использовать `boolean`?

2023-02-14 17:44 UTC, kate-lozovaya commented on packages/client/src/components/themeMessage/themeMessage.tsx
> +        <span className={style.icon} onClick={iconHandler}>Иконка реакции сердца</span>
[Исправление]
Для лучше доступности (A11y) у `span` не ставят `onClick`.
Тут можно или использовать `role="button"` и оставить `span`, либо переделать на `button`

2023-02-14 17:44 UTC, kate-lozovaya commented on packages/client/src/components/themeMessage/themeMessage.tsx
> +        <span className={classNames(style.text, amountLikes > 0 && style.textShow)}>{amountLikes} Likes</span>
[Вопрос]
Весь интерфейс русскоязычный. А тут `Likes`. Так и задумано?

2023-02-15 09:24 UTC, nullorone commented on packages/client/src/components/themeMessage/themeMessage.tsx
> +  const iconHandler = () => setCountLike((prevState) => prevState > 0 ? --prevState : ++prevState);
Не, countLike добавляет или отнимает 1 у значения лайков. Тут у меня ошибка в initialState

2023-02-15 10:13 UTC, nullorone commented on packages/client/src/components/themeMessage/themeMessage.tsx
> +        <span className={classNames(style.text, amountLikes > 0 && style.textShow)}>{amountLikes} Likes</span>
Согласно дизайну) Переводить на русский "Лайк/ов" так себе выглядит)

2023-02-15 12:05 UTC, kate-lozovaya commented on packages/client/src/components/themeMessage/themeMessage.tsx
> +  const iconHandler = () => setCountLike((prevState) => prevState > 0 ? --prevState : ++prevState);
Он берет prevState, а prevState изначально 0, в строке 14 инициализация.
То есть, когда 0, `prevState > 0 - false`, значит вернется `0+1 = 1`
Когда 1,  `prevState > 0 - true`, значит вернется `1-1 = 0`
И мы зациклились

2023-02-15 12:06 UTC, kate-lozovaya commented on packages/client/src/components/themeMessage/themeMessage.tsx
> +        <span className={classNames(style.text, amountLikes > 0 && style.textShow)}>{amountLikes} Likes</span>
Можно вообще не писать слово) 
Уже все пользователи должны иметь опыт, что сердечко = лайк

2023-02-15 12:07 UTC, kate-lozovaya requested changes

2023-02-15 12:07 UTC, kate-lozovaya commented on packages/client/src/components/themeMessage/themeMessage.tsx
> +        <span className={classNames(style.text, amountLikes > 0 && style.textShow)}>{amountLikes} Likes</span>
Вроде можно написать `role='button'` без фигурных скобок. Проверь, пожалуйста

2023-02-15 12:36 UTC, nullorone commented on packages/client/src/components/themeMessage/themeMessage.tsx
> +  const iconHandler = () => setCountLike((prevState) => prevState > 0 ? --prevState : ++prevState);
да, и ниже мы прибавляем 1 или 0 к общему значению лайков. Или я не понял в чем вопрос

2023-02-15 19:07 UTC, kate-lozovaya commented on packages/client/src/components/themeMessage/themeMessage.tsx
> +  const iconHandler = () => setCountLike((prevState) => prevState > 0 ? --prevState : ++prevState);
Не понимаю, зачем использовать числа, если можно взять `boolean` `like/не like`. И прибавлять к общему числу лайков 1, если true, и 0, если false. Потому что именно переменная countLike отвечает сейчас за наличие/отсутствие лайка

2023-02-16 08:30 UTC, kate-lozovaya commented
Ответила про лайки. 
И у тебя появился конфликт веток(
Напомню, что решать конфликты лучше через rebase, и чужие коммиты не должны появляться в твоем PR. 
Но если что-то пойдет не так, подпиши, пожалуйста, файлы, которые проверять не нужно, чтобы было удобно ревьюить

2023-02-16 10:37 UTC, nullorone commented
> Ответила про лайки. И у тебя появился конфликт веток( Напомню, что решать конфликты лучше через rebase, и чужие коммиты не должны появляться в твоем PR. Но если что-то пойдет не так, подпиши, пожалуйста, файлы, которые проверять не нужно, чтобы было удобно ревьюить

Решил разрулить через веб-интерфейс гитхаба, а он сделал коммит в виде мержа))
Но чужих коммитов не вижу, поэтому, вроде все ок?

2023-02-16 10:37 UTC, nullorone commented on packages/client/src/components/themeMessage/themeMessage.tsx
> +  const iconHandler = () => setCountLike((prevState) => prevState > 0 ? --prevState : ++prevState);
да, можно и так)

2023-02-16 12:10 UTC, nullorone commented on packages/client/src/components/themeMessage/themeMessage.tsx
> +  const iconHandler = () => setCountLike((prevState) => prevState > 0 ? --prevState : ++prevState);
На мой взгляд, стало хуже, не лаконичнее

2023-02-16 15:01 UTC, kate-lozovaya requested changes
мерж пришел хорошо, все удобно, спасибо!

2023-02-16 15:01 UTC, kate-lozovaya commented on packages/client/src/components/themeMessage/themeMessage.tsx
> +  }
[Исправление]
Два раза делаешь одно и то же действие `countLikes = props.countLikes || 0;`. Проверяешь на `undefined`, поэтому лучше использовать `??`
И тут можно в `memo` обернуть переменную, чтобы она пересчитывалась при смене `hasLike`
```suggestion
const countLikes = useMemo(() => {
  return (props.countLikes ?? 0) + hasLike;
}, [hasLike, props.countLikes])
```
Саджест написала руками, могла сделать опечатку

2023-02-16 15:34 UTC, nullorone commented on packages/client/src/components/themeMessage/themeMessage.tsx
> +  }
Складывать number и boolean законно?))

2023-02-16 20:45 UTC, kate-lozovaya commented on packages/client/src/components/themeMessage/themeMessage.tsx
> +  }
Вполне, я сложила в инспекторе )
А вообще есть [унарный +](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Unary_plus)

2023-02-17 21:31 UTC, kate-lozovaya approved these changes

2023-02-19 12:27 UTC, merged