Feature/mon 59 header component
22-reactors/monopoly pull request #23
Opened 2023-02-14 14:20 UTC by skaamoogs

### Компонент header

<img width="1385" alt="Screenshot 2023-02-14 at 20 12 30" src="https://user-images.githubusercontent.com/94950998/218764611-e74f8b3c-3f67-40df-b709-2c0360c8bf4e.png">

<img width="1378" alt="Screenshot 2023-02-14 at 20 13 03" src="https://user-images.githubusercontent.com/94950998/218764608-22cf36a4-60bb-4182-938d-a27347dee014.png">

2023-02-15 20:13 UTC, realdmitrii approved these changes
замечания не значительные, вопросы были - обсудили в пачке

2023-02-15 20:13 UTC, realdmitrii commented on packages/client/src/styles/variables.scss
> +$main-margin-left: 200px;
строку добавить, уважить гит)

2023-02-16 15:02 UTC, kate-lozovaya commented
У ветки конфликт, поправь, пожалуйста

2023-02-16 16:00 UTC, kate-lozovaya requested changes

2023-02-16 16:00 UTC, kate-lozovaya commented on packages/client/src/components/header/header.tsx
> +            <li key={link.path} className={style.li}>
[Исправление]
Класса `li` нет в `css`

2023-02-16 16:00 UTC, kate-lozovaya commented on packages/client/src/components/header/header.module.scss
> +  margin-right: 30px;
[Предложение]
Насколько я знаю, для текущего учебного проекта адаптивность не нужна. Но в обычном проекте она скорее всего будет.
Сейчас у всех компонентов с классом `link` будет правый отступ `30px`. И при уменьшении ширины экрана (и при условии, что у flex-контейнера разрешен `wrap`) в какой-то момент кнопки визуально будет вмещаться, но фактически последняя перенесется на новую строку, так как она вместе со своим margin не влезет.

Поэтому лучше такие отступы, которые должны быть только между элементами помещать в [селектор с плюсом, ищет смежные элементы](https://doka.guide/css/combined-selectors/#smezhnye-.element1-.element2)
```
.link + .link {
  margin-left: 30px;
}
```
В таком случае отступ будет применен только к тем классам link (правый), перед которыми есть класс link (левый)

2023-02-16 16:00 UTC, kate-lozovaya commented on packages/client/src/components/header/header.tsx
> +      )}
[Предложение]
Тут две вариации одного кусочка хедера. Они наверняка не будут отрисованы вместе, поэтому лучше этот кусочек вынести в отдельный компонент, поставить в нем условие на наличие/отсутствие юзера, и возвращать нужный кусочек.

Если у вас в команде разрешено делать несколько компонентов в одном файле, то можешь создать компонент ниже. Но лучше все же в папке header создать папку для подкомпонента, и вынести этот кусочек туда.
Но в крайнем случае можно прямо тут использовать тернарный оператор
```suggestion
      {user ? (
        <div className={style.user}>
          <img className={style.avatar} src={user.avatar} alt="avatar" />
          <h4 className={classNames(style.name, isDarkTheme && style.darkText)}>
            {user.display_name}
          </h4>
          <div className={style.divider}></div>
          <span
            className={classNames(
              style.logoutText,
              !isDarkTheme && style.lightText,
              isDarkTheme && style.darkText
            )}>
            {logoutText}
          </span>
        </div>
      ) : (
        <div className={style.headerButtons}>
          <Link to={links.login.path}>
            <Button
              variation={ButtonVariation.PRIMARY}
              size={ButtonSizes.MEDIUM}
              rounded>
              {links.login.title}
            </Button>
          </Link>
          <Link to={links.signup.path}>
            <Button
              variation={ButtonVariation.OUTLINED}
              size={ButtonSizes.MEDIUM}
              rounded>
              {links.signup.title}
            </Button>
          </Link>
        </div>
      )}
```

2023-02-16 16:01 UTC, kate-lozovaya commented
B можешь еще показать, как кнопки без юзера выглядят

2023-02-17 06:31 UTC, skaamoogs commented on packages/client/src/components/header/header.module.scss
> +  margin-right: 30px;
Спасибо за подсказку

2023-02-17 06:32 UTC, skaamoogs commented on packages/client/src/components/header/header.tsx
> +      )}
Да, так будет выглядеть лучше

2023-02-17 06:40 UTC, skaamoogs commented
<img width="1379" alt="Screenshot 2023-02-16 at 22 18 51" src="https://user-images.githubusercontent.com/94950998/219568609-418b3554-13b2-4cd2-a1e3-a12cb7c93a03.png">
<img width="1387" alt="Screenshot 2023-02-16 at 22 19 13" src="https://user-images.githubusercontent.com/94950998/219568634-b44a760d-04ce-450c-aa93-9be9fc19dbd8.png">

2023-02-17 09:10 UTC, kate-lozovaya requested changes

2023-02-17 09:10 UTC, kate-lozovaya commented on packages/client/src/components/header/login-buttons/login-buttons.tsx
> +
[Исправление]
Тернарник читается сложнее, чем простой if. И так как сейчас кнопки вынесены в отдельный компонент, то можно записать вот так:
```
if (user) {
  return ...
}

return ...
```

2023-02-19 08:47 UTC, kate-lozovaya approved these changes
👍🏻

2023-02-19 11:40 UTC, merged