Feature/mon 60 footer component
22-reactors/monopoly pull request #25
Opened 2023-02-14 14:55 UTC by skaamoogs

### Footer component

<img width="1384" alt="Screenshot 2023-02-14 at 20 50 59" src="https://user-images.githubusercontent.com/94950998/218773927-718fffe5-b5b7-435b-a0f6-5585ba438f43.png">

2023-02-15 23:27 UTC, Krezo commented
Привет, у меня не билдится проект

![image](https://user-images.githubusercontent.com/19520555/219215593-ecccb268-ea3f-46f9-93b2-37643095788b.png)

![image](https://user-images.githubusercontent.com/19520555/219215622-a4dcf84a-2992-4add-91d3-92a1225740b0.png)

2023-02-15 23:57 UTC, Krezo reviewed
Проверь внимательно макет, много несоответсвий от нужного цвета, до нужной высоты текста

2023-02-15 23:57 UTC, Krezo commented on packages/client/src/styles/variables.scss
> +$h4: 500 16px/22px 'Manrope', sans-serif;
Миксины текста добавили (влей dev)

2023-02-20 09:21 UTC, Krezo approved these changes

2023-02-20 21:21 UTC, kate-lozovaya requested changes

2023-02-20 21:21 UTC, kate-lozovaya commented on packages/client/src/components/footer/footer.module.scss
> +  margin: 0 0 15px 0;
[Предложение]
Если левый и правый margin одинаковые, можно написать только три значения для свойства.
`margin: верхний бока нижний`
То есть тут можно сделать так `margin: 0 0 15px;`

2023-02-20 21:21 UTC, kate-lozovaya commented on packages/client/src/components/footer/footer.tsx
> +        <nav className={style.nav}>
[Исправление]
Класса nav в стилях нет

2023-02-20 21:21 UTC, kate-lozovaya commented on packages/client/src/components/footer/footer.module.scss
> +  grid-template-columns: repeat(2, min-content);
[Вопрос]
[min-content ориентируется на одно самое длинное слово](https://developer.mozilla.org/en-US/docs/Web/CSS/grid-template-columns). То есть если будет сочетание из двух крупных слов, то они разобьются на две строки. 
Так и задумано?

2023-02-20 21:21 UTC, kate-lozovaya commented on packages/client/src/components/footer/footer.tsx
> +                  (title === links.login.title || title === links.signup.title)
[Предложение]
Сложное условие. Лучше вынести его в переменную и дать говорящее название

2023-02-21 13:25 UTC, skaamoogs commented on packages/client/src/components/footer/footer.module.scss
> +  grid-template-columns: repeat(2, min-content);
Нет, задумано не так было)
Поправил

2023-02-21 13:38 UTC, skaamoogs commented on packages/client/src/components/footer/footer.tsx
> +                  (title === links.login.title || title === links.signup.title)
Сделал

2023-02-21 13:38 UTC, skaamoogs commented on packages/client/src/components/footer/footer.tsx
> +        <nav className={style.nav}>
Убрал

2023-02-21 13:38 UTC, skaamoogs commented on packages/client/src/components/footer/footer.module.scss
> +  margin: 0 0 15px 0;
Сделал

2023-02-21 18:35 UTC, kate-lozovaya requested changes

2023-02-21 18:35 UTC, kate-lozovaya commented on packages/client/src/components/footer/footer.tsx
> +  };
[Предложение]
Сейчас функция будет пересоздаваться при каждом перерендере. 
Если передавать в функцию параметр isAuthorized, то ее можно вынести из компонента, и тогда она создастся однажды.

2023-02-22 08:13 UTC, kate-lozovaya approved these changes

2023-02-22 10:27 UTC, merged