Feature/mon 53 game engine
22-reactors/monopoly pull request #28
Opened 2023-02-15 19:07 UTC by Renovacio3429

### Какую задачу решаем

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-02-16 09:53 UTC, nullorone commented
> Задача: https://linear.app/monopoly/issue/MON-53/igrovoj-dvizhok
> 
> _Конфигурация игры:_ Конфигурация настраивается в файле monopolyConfig.ts: -Кол-во игроков (их цвет фишки, имя) -Стартовая сумма, с которой стартуют игроки -Кол-во денег, получаемых игроков при прохождении полного круга -Игроки ходят по очереди, в порядке их добавления в конфигурационный файл -Настройка карточек отображаемых на игровом поле (задний фон, их стоимость, название, цвет) -Цвет кубиков
> 
> **Внимание! Для корректной работы игры необходимо убрать React.StrictMode, иначе кубики будут кидаться дважды, как итог двигаются одновременно 2 фишки**
> 
> _Реализованные правила игры:_ Игроки ходят по очереди на кол-во ходов, которое определяется броском кубиков. Цель игры захватить как можно больше домиков.  Выкуп домика происходит автоматически, если игроку хватает денег на выкуп и он не захвачен другим игроком, в противном случае ничего не произойдет. В случае захвата с игрока списываются деньги в соответсвии с ценой домика. Для получения дополнительных денег игроку необходимо сделать полный круг. После того как все домики будут захвачены происходит подсчет кто больше всего произвел захватов, 1 домик - 1 очко, кто больше набрал очков - тот и победил. Ничья в данный момент не предусмотрена.
> 
> P.S. Код лучше взорвать базукой, надеюсь никто не ослепнет от увиденного, но свои цели он выполняет)
> 
> _Демо:_ https://user-images.githubusercontent.com/59480386/219137764-7dd5823e-1c9d-4bda-8b5f-07f5560a89f2.mp4
> 
> _Конец игры:_ <img alt="конец игры" width="1440" src="https://user-images.githubusercontent.com/59480386/219135826-33d2c810-209b-4a69-b66d-283c41004ede.png">
> 
> Касательно сборки vercel, при нажатии кнопки inspect и переходе на страницу (авторизовался через git, подтвердил свой email через смс), где можно получить статус сборки я получаю: <img alt="Screenshot 2023-02-16 at 02 53 20" width="1440" src="https://user-images.githubusercontent.com/59480386/219138439-8dbc3279-6d3d-4c7c-aff9-d2a65d83ff36.png"> Что я пробывал: проваливаться в vercel в других пул-реквестах, то же самое. У меня на ПК все работает и собирается, удалял все node_modules и прописывал yarn bootstrap, ошибок нету. А vercel кидает ошибку и я даже не знаю, что ему надо от меня т.к. посмотреть не могу(

<img width="1247" alt="image" src="https://user-images.githubusercontent.com/35527172/219331270-31d861d9-fee6-48ee-a31e-cfc30f509e85.png">

2023-02-16 10:04 UTC, Renovacio3429 commented
> > Задача: https://linear.app/monopoly/issue/MON-53/igrovoj-dvizhok
> > _Конфигурация игры:_ Конфигурация настраивается в файле monopolyConfig.ts: -Кол-во игроков (их цвет фишки, имя) -Стартовая сумма, с которой стартуют игроки -Кол-во денег, получаемых игроков при прохождении полного круга -Игроки ходят по очереди, в порядке их добавления в конфигурационный файл -Настройка карточек отображаемых на игровом поле (задний фон, их стоимость, название, цвет) -Цвет кубиков
> > **Внимание! Для корректной работы игры необходимо убрать React.StrictMode, иначе кубики будут кидаться дважды, как итог двигаются одновременно 2 фишки**
> > _Реализованные правила игры:_ Игроки ходят по очереди на кол-во ходов, которое определяется броском кубиков. Цель игры захватить как можно больше домиков.  Выкуп домика происходит автоматически, если игроку хватает денег на выкуп и он не захвачен другим игроком, в противном случае ничего не произойдет. В случае захвата с игрока списываются деньги в соответсвии с ценой домика. Для получения дополнительных денег игроку необходимо сделать полный круг. После того как все домики будут захвачены происходит подсчет кто больше всего произвел захватов, 1 домик - 1 очко, кто больше набрал очков - тот и победил. Ничья в данный момент не предусмотрена.
> > P.S. Код лучше взорвать базукой, надеюсь никто не ослепнет от увиденного, но свои цели он выполняет)
> > _Демо:_ https://user-images.githubusercontent.com/59480386/219137764-7dd5823e-1c9d-4bda-8b5f-07f5560a89f2.mp4
> > _Конец игры:_ <img alt="конец игры" width="1440" src="https://user-images.githubusercontent.com/59480386/219135826-33d2c810-209b-4a69-b66d-283c41004ede.png">
> > Касательно сборки vercel, при нажатии кнопки inspect и переходе на страницу (авторизовался через git, подтвердил свой email через смс), где можно получить статус сборки я получаю: <img alt="Screenshot 2023-02-16 at 02 53 20" width="1440" src="https://user-images.githubusercontent.com/59480386/219138439-8dbc3279-6d3d-4c7c-aff9-d2a65d83ff36.png"> Что я пробывал: проваливаться в vercel в других пул-реквестах, то же самое. У меня на ПК все работает и собирается, удалял все node_modules и прописывал yarn bootstrap, ошибок нету. А vercel кидает ошибку и я даже не знаю, что ему надо от меня т.к. посмотреть не могу(
> 
> <img alt="image" width="1247" src="https://user-images.githubusercontent.com/35527172/219331270-31d861d9-fee6-48ee-a31e-cfc30f509e85.png">

Благодарю, поправил косяк. А почему я не могу видеть эти ошибки?

2023-02-16 10:18 UTC, Renovacio3429 commented
посмотреть игру можно здесь: https://monopoly-client-qoid21udk-monopoly-reactors.vercel.app

2023-02-16 12:28 UTC, nullorone commented
> Благодарю, поправил косяк. А почему я не могу видеть эти ошибки?

Выслал тебе на почту инвайт

2023-02-16 12:29 UTC, nullorone commented
пока что вопрос - почему не всегда закрашиваются поля на которые попадает фишка?

2023-02-16 12:32 UTC, Renovacio3429 commented
> > Благодарю, поправил косяк. А почему я не могу видеть эти ошибки?
> 
> Выслал тебе на почту инвайт

Теперь работает, спасибо)

2023-02-16 12:35 UTC, Renovacio3429 commented
> пока что вопрос - почему не всегда закрашиваются поля на которые попадает фишка?

Закрашиваются только карточки, которые можно купить. Понять, что должно закрашиваться можно по цветной полоске на карточке, а остальные карты пока ничего не делают

2023-02-16 12:36 UTC, Renovacio3429 commented
> > пока что вопрос - почему не всегда закрашиваются поля на которые попадает фишка?
> 
> Закрашиваются только карточки, которые можно купить. Понять, что должно закрашиваться можно по цветной полоске на карточке, а остальные карты пока ничего не делают, хотя должны давать какие-нибудь бонусы или штрафы.

2023-02-16 16:11 UTC, nullorone approved these changes

2023-02-16 22:38 UTC, kate-lozovaya commented
Я не смогла досмотреть до конца сразу. Очень много кода. Такие PR лучше разбивать на кусочки, а то очень трудно обрабатывать. Но спасибо, что написал комментарий к PR, он очень помогает, но надо дополнить )

Можешь рассказать, что за константы используешь, как подбирал их значения. Например, константы `BASE_SIZE`, `MAIN_CARD_SIZE`, `CHIP_SHIFT`

2023-02-17 14:46 UTC, Renovacio3429 commented
> Я не смогла досмотреть до конца сразу. Очень много кода. Такие PR лучше разбивать на кусочки, а то очень трудно обрабатывать. Но спасибо, что написал комментарий к PR, он очень помогает, но надо дополнить )
> 
> Можешь рассказать, что за константы используешь, как подбирал их значения. Например, константы `BASE_SIZE`, `MAIN_CARD_SIZE`, `CHIP_SHIFT`

Сделал доп. комит с комментами)

2023-02-17 15:37 UTC, Renovacio3429 commented
Продублирую здесь на всякий случай:

Для пример возьмем первый ряд, что бы не учитывать вращение 

карточки: 

BASE_SIZE - размер обычной карточки по оси y, в случае поворота по x, относительно полного размера
MAIN_CARD_SIZE - размер обычной карточки по оси x, в случае поворота по y, относительно полного размера

Пропорции ряда следующие: в 1 ряду 2 угловые карты и 9 обычных
ширина и длина угловой карты 0.14 (14% от полного размера), ширина обычной 0.08 (8% от полного размера)
итого 14% * 2 +  8% * 9 = 100% (где 100% это полная длина по x или y)

фишки:

Координаты. 0,0 левый верхний угол карты

CHIP_SHIFT - смещение фишки относительно размера карточки по оси y, в случае поворота по x
CHIP_CENTER  - смещение фишки относительно размера карточки по оси x, в случае поворота по y

Во всех этих константах указывается относительный размер относительно полного размера
1 - полная длина или ширина

2023-02-18 07:19 UTC, kate-lozovaya commented
> Пропорции ряда следующие: в 1 ряду 2 угловые карты и 9 обычных
ширина и длина угловой карты 0.14 (14% от полного размера), ширина обычной 0.08 (8% от полного размера)
итого 14% * 2 + 8% * 9 = 100% (где 100% это полная длина по x или y)

Вот это отличное объяснение. Если бы переменные рассчитывались в коде, мне было бы понятно, как такие числа появились. А так я понимала, что это процент, но не понимала, почему он именно с таким значением

2023-02-18 11:37 UTC, Renovacio3429 commented
> > Пропорции ряда следующие: в 1 ряду 2 угловые карты и 9 обычных
> > ширина и длина угловой карты 0.14 (14% от полного размера), ширина обычной 0.08 (8% от полного размера)
> > итого 14% * 2 + 8% * 9 = 100% (где 100% это полная длина по x или y)
> 
> Вот это отличное объяснение. Если бы переменные рассчитывались в коде, мне было бы понятно, как такие числа появились. А так я понимала, что это процент, но не понимала, почему он именно с таким значением

Подправил коменты на более понятные, что-нибудь еще нужно подправить?)

2023-02-18 20:29 UTC, kate-lozovaya requested changes
Еще раз поворчу на большой PR. 
### Почему большой PR - это плохо:
1. Коллегам нужно тратить очень много времени и сил на его проверку
2. К ревью нужно морально готовиться, то есть оно может откладываться / затягиваться
3. Ревьюеру сложно держать весь контекст по PR это в голове, из-за чего может страдать качество
4. Из-за длительной проверки растут риски конфликта с главной веткой и потери актуальности PR
5. Если ревьер найдет логическую ошибку, может потребоваться полная переработка кода и идеи в целом. То есть еще + 1 условная человеконеделя, с учетом, что на PR уже потрачено много времени, звучит очень страшно!
6. Может быть много правок после ревью

Мне понадобилось 5 заходов на этот PR, и из-за того, что информация забывалась, приходилось смотреть некоторые файлы заново.

### Как можно исправить ситуацию:
1. Для фич можно проводить дизайн ревью, где один разработчик подробно описывает идею, показывает, какие компоненты будут использоваться, и как они будут взаимодействовать. 
2. Разбить фичу на кусочки. Например, тут можно было бы отдельно выкатывать карточку, кубики, фишки и поле.

В целом по PR. Код должен говорить сам за себя. Да, это все про те константы. Хотелось бы, чтобы переменные рассчитывались, а не просто были равны какому-то числу. Комментарии помогают, но именно при подсчете можно обойтись без них

2023-02-18 20:29 UTC, kate-lozovaya commented on packages/client/src/game-engine/config/monopolyConfig.ts
> +export const MonopolyConfig: IMonopolyConfig = {
[Предложение]
Тут можно написать коммент, какой параметр за что отвечает. Чтобы любой разработчик мог придти и поменять значение

2023-02-18 20:29 UTC, kate-lozovaya commented on packages/client/src/game-engine/core/card/cardComponent/cardRect.ts
> +    const color = backgroundColor ? backgroundColor : this.backgroundColor
[Исправление]
Запись можно сократить до `backgroundColor ?? this.backgroundColor`, потому что возвращается `backgroundColor`, если он есть

2023-02-18 20:29 UTC, kate-lozovaya commented on packages/client/src/game-engine/core/card/cardComponent/cardRect.ts
> +      color: color,
[Исправление]
Тут тоже можно сократить `color: color,` до `color,`. Когда названия ключа и значения совпадают, можно написать только значение

2023-02-18 20:29 UTC, kate-lozovaya commented on packages/client/src/game-engine/core/card/cardComponent/cardRect.ts
> +  private getSizesVertical(position: number, canvasSize: number) {
[Вопрос]
А почему тут `position` - индекс карточки, а не `PositionEnum`? Есть ведь функция, которая вычисляет позицию `getPosition`

2023-02-18 20:29 UTC, kate-lozovaya commented on packages/client/src/game-engine/core/card/cardComponent/cardRect.ts
> +    //размер карточки по оси y
[Вопрос]
Ту, видимо, должно быть слово фишки, а не карточки

2023-02-18 20:29 UTC, kate-lozovaya commented on packages/client/src/game-engine/core/card/cardComponent/cardRect.ts
> +    if (isTop || isBottom) {
[Предложение]
Тут проверяется position карточки. Можно получить значение  из функции getPosition
```suggestion
    const position = CardRect.getPosition(index);
    if (position === PositionEnum.Top || position === PositionEnum.Bottom) {
```

2023-02-18 20:29 UTC, kate-lozovaya commented on packages/client/src/game-engine/core/card/cardComponent/cardRect.ts
> +    const height = this.baseSize
[Вопрос]
Почему нет `this.mainSize = canvasSize * CardRect.CONST.MAIN_CARD_SIZE`?

Хочется, чтобы единообразно выглядели вычисления, чтобы было удобно их читать.

2023-02-18 20:29 UTC, kate-lozovaya commented on packages/client/src/game-engine/core/card/cardComponent/cardRect.ts
> +  }
[Предложение]
Можно взять предыдущую функцию `getSizesVertical`  и вернуть `{ height, width, y, x }`.
Код идентичный, если смотреть на переменные не как на width и height, а как на узкая часть и широкая часть (над названиями бы еще подумать)

2023-02-18 20:29 UTC, kate-lozovaya commented on packages/client/src/game-engine/core/card/cards.ts
> +    return undefined
[Исправление]
Если не писать `return undefined`, функция все равно вернет `undefined`, если дойдет до этой строки

2023-02-18 20:29 UTC, kate-lozovaya commented on packages/client/src/game-engine/core/chip/chips.ts
> +      if (i === Chips.CONST.COUNT_CARDS) {
[Предложение]
Можно объединить инкремент и условие, если записать инкрементацию в префиксной форме.
Сначала `i` увеличится на 1, потом будет сравниваться с `Chips.CONST.COUNT_CARDS`
```suggestion
      if (++i === Chips.CONST.COUNT_CARDS) {
```

2023-02-18 20:29 UTC, kate-lozovaya commented on packages/client/src/game-engine/core/winnerinfo/winnerinfo.ts
> +    ].join(' ')
[Вопрос]
Почему не строка?
```suggestion
    const userInfoText = `${winner.userName} победил (${winner.score} оч.)`
```

2023-02-18 20:29 UTC, kate-lozovaya commented on packages/client/src/game-engine/core/winnerinfo/winnerinfo.ts
> +    console.log('filltext')
[Вопрос]
Вроде тут не нужен `console.log`. Может убрать?

2023-02-18 20:29 UTC, kate-lozovaya commented on packages/client/src/game-engine/core/winnerinfo/winnerinfo.ts
> +    })
[Предложение]
Можно через [reduce](https://doka.guide/js/array-reduce/) собрать значение
```suggestion
    const winner: IUserConfig = MonopolyConfig.userConfig.reduce((res, user) => {
      if (!res || user.score > res.score) {
        return user
      }
      return res
    })
```

2023-02-18 20:29 UTC, kate-lozovaya commented on packages/client/src/game-engine/gameEngine.ts
> +      if (userMoney > cardPrice) {
[Вопрос]
Почему если суммы равны нельзя покупать карточку?

2023-02-18 20:29 UTC, kate-lozovaya commented on packages/client/src/pages/game/game.module.scss
> +  overflow-y: scroll !important;
[Исправление]
`!important` - плохо! Потом будет трудно (почти невозможно) переопределить стиль
Можно ли его отсюда убрать?

2023-02-19 10:16 UTC, Renovacio3429 commented on packages/client/src/game-engine/gameEngine.ts
> +      if (userMoney > cardPrice) {
Не учел этот момент, мой косяк)

2023-02-19 10:16 UTC, Renovacio3429 commented on packages/client/src/game-engine/core/winnerinfo/winnerinfo.ts
> +    console.log('filltext')
Да, остался после отладки

2023-02-19 10:33 UTC, Renovacio3429 commented on packages/client/src/game-engine/core/card/cardComponent/cardRect.ts
> +  }
Не совсем идентичный, так же есть отличия по константам, например в getSizesHorizontal при формировании x и y используется сравнение с CardRect.CONST.INDEX_BOTTOM_LEFT, а в getSizesVertical с CardRect.CONST.INDEX_TOP_RIGHT, а так же расчет координат которые не являются базовыми:

У getSizesVertical
const y =
      cardIndex < CardRect.CONST.INDEX_TOP_RIGHT
        ? 0
        : canvasSize - this.baseSize

У getSizesHorizontal
const x =
      cardIndex < CardRect.CONST.INDEX_BOTTOM_LEFT
        ? canvasSize - this.baseSize
        : 0

По пробывал поиграться с if'aми, получилась каша не читаемая. Решил оставить как есть из соображения, что положения у карточки может быть всего 2: вертикальное и горизонтальное

2023-02-19 10:38 UTC, Renovacio3429 commented
Константы расположения фишки на карточке решил оставить т.к. принцип заключается в том, что я смотрю на визуал и делаю вывод нравиться мне такой внешний вид или нет, то есть никакой математической зависимости от чего либо нету

2023-02-19 10:40 UTC, Renovacio3429 commented
> Еще раз поворчу на большой PR.
> 
> ### Почему большой PR - это плохо:
> 1. Коллегам нужно тратить очень много времени и сил на его проверку
> 2. К ревью нужно морально готовиться, то есть оно может откладываться / затягиваться
> 3. Ревьюеру сложно держать весь контекст по PR это в голове, из-за чего может страдать качество
> 4. Из-за длительной проверки растут риски конфликта с главной веткой и потери актуальности PR
> 5. Если ревьер найдет логическую ошибку, может потребоваться полная переработка кода и идеи в целом. То есть еще + 1 условная человеконеделя, с учетом, что на PR уже потрачено много времени, звучит очень страшно!
> 6. Может быть много правок после ревью
> 
> Мне понадобилось 5 заходов на этот PR, и из-за того, что информация забывалась, приходилось смотреть некоторые файлы заново.
> 
> ### Как можно исправить ситуацию:
> 1. Для фич можно проводить дизайн ревью, где один разработчик подробно описывает идею, показывает, какие компоненты будут использоваться, и как они будут взаимодействовать.
> 2. Разбить фичу на кусочки. Например, тут можно было бы отдельно выкатывать карточку, кубики, фишки и поле.
> 
> В целом по PR. Код должен говорить сам за себя. Да, это все про те константы. Хотелось бы, чтобы переменные рассчитывались, а не просто были равны какому-то числу. Комментарии помогают, но именно при подсчете можно обойтись без них

Мне кажется тут есть косяк в самой постановке задаче: придумайте

2023-02-19 10:53 UTC, kate-lozovaya approved these changes
Апрув получен. Но не делай такие большие PR, пожалуйста )

2023-02-19 11:35 UTC, merged