Feature/mon 63 paginator
22-reactors/monopoly pull request #30
Opened 2023-02-19 14:46 UTC by nullorone

### Добавляет компонент Paginator

<img width="209" alt="image" src="https://user-images.githubusercontent.com/35527172/219955384-a80c63ac-7ffb-4d23-a659-15856f53c151.png">

<img width="222" alt="image" src="https://user-images.githubusercontent.com/35527172/219955457-e1e3a66c-aa5b-4ca4-a55b-1c2178ed56a3.png">

2023-02-19 17:18 UTC, Renovacio3429 commented
Как дополнительный вариант, если мы не хотим заморачиваться я думаю можно использовать готовую пагинацию:
https://www.npmjs.com/package/react-paginate

2023-02-19 22:21 UTC, Renovacio3429 requested changes

2023-02-19 22:21 UTC, Renovacio3429 commented on packages/client/src/components/paginator/paginator.tsx
> +        const newFirstPage = pages[0] - 1;
Не понял когда должен срабатывать этот код, при переходе на 2 страницу и назад стрелочкой переменная page = 2 (хотя должно быть 1 насколько я понял), и в таком случае до этого кода мы никогда не доходим, при чем так же и с последующими страницами, при переходе с 3 страницы на 2 страницу переменная page = 3 и т.д. (я передал пропсы [1, 2, 3, 4, 5])

<img width="1440" alt="Screenshot 2023-02-20 at 00 07 14" src="https://user-images.githubusercontent.com/59480386/219963375-07be7482-b468-4d87-b22b-72068bf59e31.png">
<img width="1440" alt="Screenshot 2023-02-20 at 00 08 18" src="https://user-images.githubusercontent.com/59480386/219963383-20a80814-3b60-4ad6-8255-82223293a7c5.png">

А если этот код  и сработает, по условиям выше переменная page должна быть равна page[0] я получу страницу 0, при переходе на 1 страницу. Для примера я закомментировал блокирующий участок и перешел с 2 страницы на страницу 1:

<img width="1440" alt="Screenshot 2023-02-20 at 00 45 32" src="https://user-images.githubusercontent.com/59480386/219965523-68062a15-b522-4ff7-adfc-bb5f1be53ace.png">
<img width="1440" alt="Screenshot 2023-02-20 at 00 46 08" src="https://user-images.githubusercontent.com/59480386/219965536-8cbffd0e-e5e0-4702-a615-74e7088f31ca.png">

Причем с 0 страницы можно перейти на -1 страницу и т.д.

2023-02-19 22:21 UTC, Renovacio3429 commented on packages/client/src/components/paginator/paginator.tsx
> +        const newLastPage = pages[pages.length - 1] + 1;
Я передал пропсы [1, 2, 3, 4, 5] и здесь я получаю новую последнюю страницу 6, которой нету в пропсах и так можно до бесконечности генерировать новые страницы, которых не существует

<img width="1440" alt="Screenshot 2023-02-20 at 00 14 29" src="https://user-images.githubusercontent.com/59480386/219963696-8188cee3-69dd-489d-8321-875e08002b5d.png">

<img width="1440" alt="Screenshot 2023-02-20 at 00 15 21" src="https://user-images.githubusercontent.com/59480386/219963706-ec314463-f0f1-4652-aa78-f40fa5e7c521.png">

2023-02-20 03:31 UTC, Renovacio3429 commented
А помимо этого компонента будет еще какой-то пагинатор? Не понял куда надо передавать данные, которые должны отображаться, что бы этот компонент сам по ним отрисовывал таблицу с данными с нужным кол-вом записей

2023-02-20 03:40 UTC, nullorone commented
> А помимо этого компонента будет еще какой-то пагинатор? Не понял куда надо передавать данные, которые должны отображаться, что бы этот компонент сам по ним отрисовывал таблицу с данными с нужным кол-вом записей

компонент ничего не должен знать об окружении где он используется. Ты смотришь на лидерборд, а пагинатор еще используется в форуме, например.

2023-02-20 03:41 UTC, nullorone commented on packages/client/src/components/paginator/paginator.tsx
> +        const newLastPage = pages[pages.length - 1] + 1;
да, понял, что не ту бизнес-логику реализовал))

2023-02-20 03:42 UTC, nullorone commented on packages/client/src/components/paginator/paginator.tsx
> +        const newFirstPage = pages[0] - 1;
Не знаю как у тебя получилось дойти до 0, но в коде есть условие, что если page === 1 то мы ничего не делаем и просто выходим из обработчика через return;

2023-02-20 03:44 UTC, nullorone commented
> Как дополнительный вариант, если мы не хотим заморачиваться я думаю можно использовать готовую пагинацию: https://www.npmjs.com/package/react-paginate Здесь нужно добавить только css

да ну, че там заморачиваться) либа-компонент избыточна наворотами и пропсами, кмк

2023-02-20 04:12 UTC, Renovacio3429 commented on packages/client/src/components/paginator/paginator.tsx
> +        const newFirstPage = pages[0] - 1;
Попробуй закоментить как в скрине второй if и перейти с 2 страницы на 1 (из-за этого условие код ниже никогда не выполняется), я просто твой компонент вставил в свою страницу. Причем на скриншоте видно что условие page === 1 осталось, но оно не отработало т.к. значение это переменной было page = 2, выше скрин с логированием в консоли. Еще нужно передать пропсы, у меня это было props = {[1 , 2, 3, 4, 5]}.

2023-02-20 04:15 UTC, Renovacio3429 commented
> > А помимо этого компонента будет еще какой-то пагинатор? Не понял куда надо передавать данные, которые должны отображаться, что бы этот компонент сам по ним отрисовывал таблицу с данными с нужным кол-вом записей
> 
> компонент ничего не должен знать об окружении где он используется. Ты смотришь на лидерборд, а пагинатор еще используется в форуме, например.

А где будет задавать параметр, сколько записей будет отображаться? Я с 0 никогда пагинация никогда не делал, но все библиотеки по этой теме дают возможность выставить значение, сколько мы видим записей 25, 50, 100, 1000 и т.д.

2023-02-20 04:30 UTC, nullorone commented
> > > А помимо этого компонента будет еще какой-то пагинатор? Не понял куда надо передавать данные, которые должны отображаться, что бы этот компонент сам по ним отрисовывал таблицу с данными с нужным кол-вом записей
> > 
> > 
> > компонент ничего не должен знать об окружении где он используется. Ты смотришь на лидерборд, а пагинатор еще используется в форуме, например.
> 
> А где будет задавать параметр, сколько записей будет отображаться? Я с 0 никогда пагинацию никогда не делал, но все библиотеки по этой теме дают возможность выставить значение, сколько мы видим записей на странице 25, 50, 100, 1000 и т.д.

я думаю, это будет задаваться со страницы, которая будет получать по апи кол-во записей. Мы ведь можем не сразу все записи грузить, а как раз по-странично и сохранять в стор

2023-02-20 08:37 UTC, Renovacio3429 approved these changes

2023-02-20 20:45 UTC, kate-lozovaya requested changes

2023-02-20 20:45 UTC, kate-lozovaya commented on packages/client/src/components/paginator/paginator.module.scss
> +      background-image: url('arrow-light-left.svg');
[Предложение]
Не могу комментить картинки, поэтому напишу тут.
[Можно контролировать цвет svg через color](https://drbrain.ru/articles/css-currentcolor-and-svg/). Для этого надо в самой svg поставить `currentColor` вместо цвета для `fill` или `stroke` в его `path`. И тогда не буду нужны две картинки, можно будет просто менять color для класса `arrowBack`

2023-02-20 20:45 UTC, kate-lozovaya commented on packages/client/src/components/paginator/paginator.module.scss
> +.container {
[Вопрос]
А что будет, если страниц очень много? Не нужно ли скрыть все, что не входит в границы контейнера?

2023-02-20 20:45 UTC, kate-lozovaya commented on packages/client/src/components/paginator/paginator.tsx
> +  pages?: number[];
[Вопрос]
В каком случае pages не будут передаваться?

2023-02-20 20:45 UTC, kate-lozovaya commented on packages/client/src/components/paginator/paginator.tsx
> +          const firstPagesNumber = pages.at(0)!;
[Предложение]
Попробуй поставить тип для `const [pages, setPages] = useState<number[]>(DEFAULT_PAGES);`. Может тогда не надо будет ставить `!`

2023-02-20 20:45 UTC, kate-lozovaya commented on packages/client/src/components/paginator/paginator.tsx
> +          const lastPagesNumber = pages.at(-1);
[Предложение]
Думаю, тут лучше переименовать `lastPagesNumber` -> `lastVisiblePage`. И аналогично поступить с `firstPagesNumber` -> `firstVisiblePage`.
Пришлось воспроизводить в голове алгоритм, чтобы понять, для чего нужна переменная

2023-02-20 20:45 UTC, kate-lozovaya commented on packages/client/src/components/paginator/paginator.module.scss
> +.container {
Увидела, что всегда видно определенное число страниц

2023-02-20 20:45 UTC, kate-lozovaya commented on packages/client/src/components/paginator/paginator.tsx
> +  const [pages, setPages] = useState(DEFAULT_PAGES);
[Предложение]
Можно передать в пропсах количество страниц, которое будет видно, и по нему генерировать массив. 
Почему хардкодятся три страницы?

2023-02-21 05:20 UTC, nullorone commented on packages/client/src/components/paginator/paginator.module.scss
> +      background-image: url('arrow-light-left.svg');
но тогда придется вставить svg как элемент разметки и мы потеряем возможность кэширования этой свг, в отличии от фоновой вставки или через img

2023-02-21 05:21 UTC, nullorone commented on packages/client/src/components/paginator/paginator.tsx
> +  pages?: number[];
Верное подмечено. Наверное, стоит делать обязательной пропсу и отталкиваться от неё

2023-02-21 05:37 UTC, nullorone commented on packages/client/src/components/paginator/paginator.tsx
> +          const firstPagesNumber = pages.at(0)!;
частично помогло, но пришлось кастануть, чтобы окончательно побороть возмущения тс

2023-02-21 05:40 UTC, nullorone commented on packages/client/src/components/paginator/paginator.tsx
> +  const [pages, setPages] = useState(DEFAULT_PAGES);
Хотел так сделать, но столкнулся с тем, что передавая кол-во страниц, я генерирую массив внутри компонента и при каждом срабатывании стейта(он срабатывает при любом взаимодействии со стрелками или номерами страниц) у меня генерируется этот массив заново, хотя не нужно. Пробовал оборачивать в useCallback, но не помогло.

2023-02-21 08:17 UTC, kate-lozovaya requested changes
Использование as - не очень хорошая практика. Так и до as any as что-то недалеко )
С TS надо быть честным.
Я бы лучше использовала дефолтные значения

2023-02-21 08:17 UTC, kate-lozovaya commented on packages/client/src/components/paginator/paginator.tsx
> +  const [pages, setPages] = useState(DEFAULT_PAGES);
А пробовал мемоизировать переменную для массива?
```
const defaultVisiblePages = useMemo(() => {
  return Array(props.pagesCount).fill().map((_, i) => i + 1);
}, [props.pagesCount])
```
В таком случае она не должна пересчитываться, если не меняется значение пропса

2023-02-21 08:17 UTC, kate-lozovaya commented on packages/client/src/components/paginator/paginator.tsx
> +  const visiblePages = props.pages.slice(0, 3) as number[];
[Предложение]
as - не та штука, которую надо часто использовать, это скорее хак для обхода TS.
props.pages - массив чисел, значит и его слайс тоже таким будет
Если TS ругается, лучше поставить дефолтное значение, чем as number[]

2023-02-21 08:23 UTC, kate-lozovaya commented
У меня появился resolve! Ура!

2023-02-21 18:43 UTC, kate-lozovaya approved these changes
Старайтесь резолвить комментарии друг другу. Чтобы наверняка было понятно, что вопрос решен, и всем в команде понятен статус по вопросу.
Хорошая практика - когда ревьювер сам резолвит, так как именно он задает вопрос

2023-02-22 05:59 UTC, merged