Feature/mon 49 api auth
22-reactors/monopoly pull request #31
Opened 2023-02-19 17:00 UTC by skaamoogs

### Создает классы API авторизации и контроллера
### Подключает API к страницам Логина и Регистрации

Логин (видео):
https://user-images.githubusercontent.com/94950998/219962804-e8a80d3b-d43d-47c0-a3d9-163e8663f16f.mov

Регистрация (видео):
https://user-images.githubusercontent.com/94950998/219962814-ed47f032-82b6-4abf-ac13-8c97c24da3ff.mov

2023-02-20 07:47 UTC, nullorone commented on packages/client/src/api/auth/interfaces.ts
> +export type UserResponse = IUserData | IBadResponse;
нужна последняя пустая строка

2023-02-20 07:48 UTC, nullorone commented on packages/client/src/app.tsx
> +  {
зачем изменения в этом файле?

2023-02-20 07:52 UTC, nullorone commented on packages/client/src/controllers/auth.controller.ts
> +import API, { AuthAPI } from '../api/auth/auth.api';
нейминг файла можно сократить до auth.ts. Так как файл и так лежит в директории controllers

2023-02-20 07:53 UTC, nullorone commented on packages/client/src/api/auth/auth.api.ts
> +import RequestTransport from '../../service/request/request';
нейминг файла можно сократить до auth.ts. Так как файл лежит в директории api

2023-02-20 07:53 UTC, nullorone commented on .gitignore
> +.DS_Store
не хватает пустой строки в конце

2023-02-20 07:57 UTC, nullorone commented on packages/client/src/controllers/auth.controller.ts
> +      if (response == 'OK') {
почему используешь не строгое сравнение?

2023-02-20 08:04 UTC, nullorone commented on yarn.lock
>    resolved "https://registry.yarnpkg.com/@remix-run/router/-/router-1.3.1.tgz#3bb0b6ddc0a276e8dc1138d08f63035e4e23e8bf"
думаю, изменений в этом файле быть не должно. Ты ведь не добавлял никаких новых библиотек

2023-02-20 08:04 UTC, nullorone requested changes
Нужно чуть-чуть поправить

2023-02-20 09:28 UTC, skaamoogs commented on packages/client/src/app.tsx
> +  {
Вынес игру за пределы Home, когда проверял переходы. Но это в принципе к этому PR не относится, могу убрать

2023-02-20 09:29 UTC, skaamoogs commented on packages/client/src/controllers/auth.controller.ts
> +      if (response == 'OK') {
Не специально) Исправлю

2023-02-20 09:32 UTC, skaamoogs commented on yarn.lock
>    resolved "https://registry.yarnpkg.com/@remix-run/router/-/router-1.3.1.tgz#3bb0b6ddc0a276e8dc1138d08f63035e4e23e8bf"
Добавлял, но потом убрал. Может его вообще в игнор добавить?

2023-02-20 14:53 UTC, nullorone commented on packages/client/src/pages/home/home.tsx
> +      <Header {...headerProps} />
семантически, header должен быть перед main, а после main идет footer

2023-02-20 14:57 UTC, nullorone requested changes
поправить одну мелочь

2023-02-20 14:57 UTC, nullorone commented on yarn.lock
>    resolved "https://registry.yarnpkg.com/@remix-run/router/-/router-1.3.1.tgz#3bb0b6ddc0a276e8dc1138d08f63035e4e23e8bf"
не, в игнор не нужно добавлять. Разрастется и мы об этом не узнаем)

2023-02-20 15:15 UTC, skaamoogs commented on packages/client/src/pages/home/home.tsx
> +      <Header {...headerProps} />
footer еще не прошел ревью. header вынес за пределы main

2023-02-20 16:03 UTC, nullorone approved these changes

2023-02-20 18:40 UTC, kate-lozovaya requested changes

2023-02-20 18:40 UTC, kate-lozovaya commented on packages/client/src/components/header/login-buttons/login-buttons.tsx
> +  };
[Предложение]
Не очень нравится, что в компонент протекает логика. 
Если есть 100% уверенность, что нигде больше компонент использоваться не будет, ладно, но переиспользовать функции тоже не получится.
Здесь можно было бы завести виджеты, которые бы использовали компонент вместе с логикой. А саму логику перенести в хук.
Но если компонент и логика точно переиспользоваться в проекте не будет, ничего не исправляй, просто прими во внимание, что их лучше разделять.

2023-02-20 18:40 UTC, kate-lozovaya commented on packages/client/src/pages/login/login.tsx
> +    const target = event.target as typeof event.target & {
[Вопрос]
А что не так без `as typeof event.target`?

2023-02-20 18:40 UTC, kate-lozovaya commented on packages/client/src/pages/register/register.tsx
> +      login: { value: string };
[Предложение]
Уже написала в другом PR, что можно вынести тип `{ value: string }`

2023-02-20 18:40 UTC, kate-lozovaya commented on packages/client/src/service/request/request.ts
> +  method?: string;
[Предложение]
То же самое есть в другом PR. В таком случае лучше выкатывать PR для одной ветки, и после его мержа для второй вестки сделать ребейз на главную ветку, и после этого уже можно создавать PR для второй ветки, чтобы ревьюерам было проще проверять

2023-02-21 06:14 UTC, skaamoogs commented on packages/client/src/components/header/login-buttons/login-buttons.tsx
> +  };
Ну вообще запрос пользователя будет использоваться и на дургих страницах. О каких виджетах идет речь? Возможно здесь лучше сделать HOC withUser?

2023-02-21 06:52 UTC, skaamoogs commented on packages/client/src/pages/login/login.tsx
> +    const target = event.target as typeof event.target & {
Без этого TS ругается

2023-02-21 06:52 UTC, skaamoogs commented on packages/client/src/pages/register/register.tsx
> +      login: { value: string };
Вынес

2023-02-21 06:54 UTC, skaamoogs commented on packages/client/src/service/request/request.ts
> +  method?: string;
Согласен, но так еще больше времени будет занимать разработка, пока ждешь мерджа

2023-02-21 09:21 UTC, skaamoogs commented on packages/client/src/components/header/login-buttons/login-buttons.tsx
> +  };
Запрос пользователя перенес в хук. Logout оставил здесь, т.к. он только здесь использоваться будет. В принципе этот компонент только в header  используется, а сам header использоваться один раз будет.

2023-02-21 18:46 UTC, kate-lozovaya commented on packages/client/src/components/header/login-buttons/login-buttons.tsx
> +  };
> О каких виджетах идет речь?

У меня в проекте есть слой виджетов. В нем происходит связка ui-компонентов - только верстка, с хуком, в котором есть логика

2023-02-21 18:46 UTC, kate-lozovaya commented on packages/client/src/pages/login/login.tsx
> +    const target = event.target as typeof event.target & {
А можешь показать, что за ошибка

2023-02-21 18:54 UTC, kate-lozovaya commented on packages/client/src/service/request/request.ts
> +  method?: string;
Тут палка о двух концах. Либо PR позже выкладывается, либо ревьюверы тратят больше времени на проверку одних и тех же строк. Причем каждый раз могут найти к чему придраться, и может потребоваться больше времени на правки.
Но у вас сейчас жесткие рамки по срокам, поэтому не так критично, что PR-ы частично совпадают )

2023-02-21 19:02 UTC, kate-lozovaya approved these changes
as не стоит часто использовать, это принудительное проставление типа, то есть вся суть TS ломается. Иногда с ним сложно, но лучше сделать доп проверку на тип, чем упасть )

2023-02-22 06:04 UTC, skaamoogs commented on packages/client/src/pages/login/login.tsx
> +    const target = event.target as typeof event.target & {
Если вообще не утверждать тип, то он не может найти нужные свойтсва у target (Property 'login' does not exist on type 'EventTarget'.ts(2339)). Если утверждать без event.target то он не может ковертировать (Type 'EventTarget' is missing the following properties from type '{ email: { value: string; }; password: { value: string; }; }': email, password ts(2352)). Но теперь когда я вынес сбор данных формы в отдельную функцию, там уже утверждать тип не нужно.

2023-02-22 06:18 UTC, merged