Feature/mon 50 api user
22-reactors/monopoly pull request #32
Opened 2023-02-20 12:46 UTC by skaamoogs

### Создает классы API и контроллера профиля
### Подключает API к странице профиля

Смена аватара (видео):
https://user-images.githubusercontent.com/94950998/220111842-ce6df88f-c176-40cf-bd50-47897377d0eb.mov

Изменение профиля (видео):
https://user-images.githubusercontent.com/94950998/220111925-4e430563-950d-42df-a57d-faf250ee21e6.mov

2023-02-20 13:43 UTC, Renovacio3429 approved these changes

2023-02-20 18:21 UTC, kate-lozovaya requested changes

2023-02-20 18:21 UTC, kate-lozovaya commented on packages/client/src/components/info/info.tsx
> +  email: { value: string };
[Предложение]
Может вынести тип `{ value: string }`?

2023-02-20 18:21 UTC, kate-lozovaya commented on packages/client/src/components/info/info.tsx
> +            }
[Предложение]
Сложное условие получилось, трудно читается
Лучше его вынести, можно в функцию
```
const function getFieldValue(field_id) {
  if (field_id in fieldInput) {
    return fieldInput[field_id];
  }
  if (profile !== null && field_id in profile) {
    return profile[field_id]
  }
  return '';
}
```

2023-02-20 18:21 UTC, kate-lozovaya commented on packages/client/src/controllers/user.ts
> +  async changePassword(data: IPasswordData) {
[Вопрос]
А где будет происходить изменение пароля?

2023-02-20 18:21 UTC, kate-lozovaya commented on packages/client/src/api/user/user.ts
> +    });
[Вопрос]
Что будет делать searchUser?
По названию кажется, что она должна получить (?) пользователя с сервера по логину. Но тогда непонятно, почему используется post, а не get

2023-02-21 12:18 UTC, skaamoogs commented on packages/client/src/controllers/user.ts
> +  async changePassword(data: IPasswordData) {
На странице профиля, просто в текущей верстке это не реализовано

2023-02-21 12:18 UTC, skaamoogs commented on packages/client/src/components/info/info.tsx
> +  email: { value: string };
Сделал

2023-02-21 12:18 UTC, skaamoogs commented on packages/client/src/components/info/info.tsx
> +            }
Сделал

2023-02-21 12:21 UTC, skaamoogs commented on packages/client/src/api/user/user.ts
> +    });
searchUser ищет пользователя по логину. Используется post в соответствии с описанием API на https://ya-praktikum.tech/api/v2/swagger/#/
В классе API я его реализовал, но пока не ясно будем ли мы это использовать.

2023-02-21 19:26 UTC, kate-lozovaya commented on packages/client/src/components/info/info.tsx
> +      return profile[fieldId as keyof IProfileForm];
[Предложение]
в функцию передается `fieldId: string`, поэтому TS ругается. 
В интерфейсе `FieldInfo` тип `id` - ключи `IProfileForm`. 
Попробуй поправить. Если за минут 30 не получится, оставь так

2023-02-21 19:26 UTC, kate-lozovaya commented on packages/client/src/api/user/user.ts
> +    });
Поняла, спасибо!

2023-02-21 19:27 UTC, kate-lozovaya approved these changes
А как коммитишь правки по ревью? 
Почему-то не могу посмотреть коммиты после ревью, их количество совпадает с общим количеством коммитов

<img width="392" alt="image" src="https://user-images.githubusercontent.com/25737137/220439968-fe822300-68fc-412f-bdd1-74f9b29317a7.png">

2023-02-22 05:44 UTC, skaamoogs commented
> А как коммитишь правки по ревью? Почему-то не могу посмотреть коммиты после ревью, их количество совпадает с общим количеством коммитов
> 
> <img alt="image" width="392" src="https://user-images.githubusercontent.com/25737137/220439968-fe822300-68fc-412f-bdd1-74f9b29317a7.png">
 
Возможно это из-за rebase dev?

2023-02-22 05:45 UTC, merged

2023-02-22 08:15 UTC, kate-lozovaya commented
> > А как коммитишь правки по ревью? Почему-то не могу посмотреть коммиты после ревью, их количество совпадает с общим количеством коммитов
> > <img alt="image" width="392" src="https://user-images.githubusercontent.com/25737137/220439968-fe822300-68fc-412f-bdd1-74f9b29317a7.png">
> 
>   Возможно это из-за rebase dev?

Да, может быть из-за этого. Если нет конфликта, лучше не ребейзиться