Feature/mon 18 home page view
22-reactors/monopoly pull request #33
Opened 2023-02-22 17:22 UTC by skaamoogs

### Создает layout с header и footer, внутри рендерятся остальные страницы
### Создает главную страницу

Light Theme:
<img width="1648" alt="Screenshot 2023-02-22 at 23 20 25" src="https://user-images.githubusercontent.com/94950998/220706431-fec7e86a-b241-48d8-acf7-5cf97ce2cc9e.png">

Dark Theme:
<img width="1647" alt="Screenshot 2023-02-22 at 23 18 09" src="https://user-images.githubusercontent.com/94950998/220705918-5a6b2c35-b58b-4a5d-a9aa-6364873dad21.png">

2023-02-22 22:07 UTC, Renovacio3429 approved these changes

2023-02-22 22:07 UTC, Renovacio3429 commented on packages/client/src/pages/home/home.tsx
> +      {isAuthorized && <></>}
Это заглушка?

2023-02-22 22:07 UTC, Renovacio3429 commented on packages/client/src/pages/home/home.tsx
> +  const { title, description, linkText, isAuthorized, isDarkTheme } = props;
[Предложение]
У тебя выше есть интерфейс нужных пропсов IHomeProps, и ты можешь сделать деструктурирующее присваивание по нему:  **const { ...foo }: INTEFACE = e** , а дальше извлекать нужное поле из переменной foo.

2023-02-23 06:42 UTC, skaamoogs commented on packages/client/src/pages/home/home.tsx
> +  const { title, description, linkText, isAuthorized, isDarkTheme } = props;
Поясни, плиз, в чем бонус такого действия. Я деструктурирую, чтобы не писать потом props

2023-02-23 07:29 UTC, skaamoogs commented on packages/client/src/pages/home/home.tsx
> +      {isAuthorized && <></>}
Да, это заглушка для главной, если авторизован

2023-02-23 07:40 UTC, skaamoogs commented
@Renovacio3429 Посмотри еще раз, пожалуйста, я там стили пофиксил и api прикрутил к home и footer

2023-02-23 14:16 UTC, Renovacio3429 commented on packages/client/src/pages/home/home.tsx
> +  const { title, description, linkText, isAuthorized, isDarkTheme } = props;
Ну да, согласен, с тем же успехом можно из пропсов взять эти поля. Просто не понравилось такое большое количество полей при деструктуризации.

2023-02-23 14:16 UTC, Renovacio3429 approved these changes

2023-02-25 08:38 UTC, kate-lozovaya requested changes

2023-02-25 08:38 UTC, kate-lozovaya commented on packages/client/src/components/header/header.module.scss
[Исправление]
Коммент к строчке 8 `padding: 10px $main-margin;`
У меня 13 дюймовый ноутбук. И хедер с боковыми паддингами `405px` в экран не влезает.
Тоже самое с футером
Варианты решения:
1. можно адаптировать отступ
2. добавить контейнер в хедер и поставить его в центр
3. убрать отступы и поставить `space-around` для `header`

2023-02-25 08:38 UTC, kate-lozovaya commented on packages/client/src/components/header/login-buttons/login-buttons.tsx
> +    const avatar = `${resourceURL}${user?.avatar}`;
[Вопрос]
А что если `user` будет `undefined`?
Можно еще добавить дефолтный аватар. Но не к этой задаче.

2023-02-25 08:38 UTC, kate-lozovaya commented on packages/client/src/icons/logo.tsx
> +        fill="#474646"
[Предложение]
В `fill` можно записать [currentColor](https://doka.guide/css/currentcolor/). И тогда можно будет контролировать цвет `svg`, через свойство `color`

2023-02-25 08:38 UTC, kate-lozovaya commented on packages/client/src/pages/layout/layout.module.scss
> +  height: 100vh;
[Вопрос]
А зачем ограничивать высоту `wrapper`? Его контент может выходить за границы одного экрана.
Если задача - сделать `wrapper` не меньше одного экрана, можно использовать `min-height: 100vh`

2023-02-25 08:38 UTC, kate-lozovaya commented on packages/client/src/pages/home/home.module.scss
> +  min-height: $main-window-height;
[Вопрос]
Почему используется абсолютное значение, а не относительное? На моем ноутбуке это полтора экрана :)

2023-02-25 08:38 UTC, kate-lozovaya commented on packages/client/src/pages/home/home.tsx
> +      {user && <></>}
[Предложение]
Можно не писать это условие. Или тут планируется что-то добавить?
Если да, лучше вынести в отдельный компонент и через if проверять, что возвращать

2023-02-25 08:38 UTC, kate-lozovaya commented on packages/client/src/pages/home/home.module.scss
> +  justify-content: space-between;
[Исправление]
Из-за того, что элементы (текст и картинка) пытаются встать по разным сторонам, у меня они вообще не влезают. 

Как можно исправить:
1. Уменьшать значение переменной `$main-margin` в зависимости от ширины экрана (это и хедеру с футером поможет)
2. Использовать относительные единицы
3. Сделать картинку поменьше и спозиционировать ее абсолютно, чтобы она всегда прибивалась к правому краю экрана. Но текст может наезжать на картинку в таком случае, нужно посмотреть, ок ли это, обычно тексту тень добавляют, чтобы его было видно

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/25737137/221347191-d29e511a-d4d9-4882-80a4-76bc8258f283.png">

2023-02-25 08:38 UTC, kate-lozovaya commented on packages/client/src/pages/home/home.module.scss
> +  line-height: 88px;
[Предложение]
В проекте есть миксины на текст. Может можно здесь использовать один из них?

2023-02-25 08:38 UTC, kate-lozovaya commented on packages/client/src/pages/home/home.tsx
> +            <h2 className={style.description}>{description}</h2>
[Вопрос]
Точно ли `description` является заголовком семантически?

2023-02-26 08:05 UTC, skaamoogs commented on packages/client/src/components/header/login-buttons/login-buttons.tsx
> +    const avatar = `${resourceURL}${user?.avatar}`;
Если user undefined, рендерятся кнопки Войти и Регистрация. Но вот если в user avatar не задан, то да, надо бы дефолтный добавить.

2023-02-26 08:06 UTC, skaamoogs commented on packages/client/src/components/header/header.module.scss
Сделал отступ в %

2023-02-26 08:22 UTC, skaamoogs commented on packages/client/src/pages/layout/layout.module.scss
> +  height: 100vh;
Убрал

2023-02-26 08:39 UTC, skaamoogs commented on packages/client/src/pages/home/home.module.scss
> +  min-height: $main-window-height;
Потому что на макете так. Убрал, но высота все равно определяется картинкой с карточками.

2023-02-26 08:42 UTC, skaamoogs commented on packages/client/src/pages/home/home.tsx
> +      {user && <></>}
Да, тут будет экран главной, когда пользователь авторизован. А зачем выносить в отдельный компонент, если кроме этого здесь ничего нет, только обертка.

2023-02-26 08:43 UTC, skaamoogs commented on packages/client/src/pages/home/home.module.scss
> +  justify-content: space-between;
Сделал относительные единицы.

2023-02-26 08:45 UTC, skaamoogs commented on packages/client/src/pages/home/home.module.scss
> +  line-height: 88px;
Такого миксина не было, но я добавил

2023-02-26 08:53 UTC, skaamoogs commented on packages/client/src/pages/home/home.tsx
> +            <h2 className={style.description}>{description}</h2>
Просто он h2 подходил по типографике, заменил на p

2023-02-26 16:13 UTC, kate-lozovaya requested changes
Ответила в нескольких прошлых комментах. Посмотри, пожалуйста 
Все еще есть горизонтальный скролл из-за того, что картинка не влезает

https://user-images.githubusercontent.com/25737137/221422273-304142ef-807b-4d3e-b209-53ecef023729.mov

2023-02-26 16:13 UTC, kate-lozovaya commented on packages/client/src/components/header/login-buttons/login-buttons.tsx
> +    const avatar = `${resourceURL}${user?.avatar}`;
Лучше добавить дефолтный (в другой задаче и другом PR)

2023-02-26 16:13 UTC, kate-lozovaya commented on packages/client/src/pages/home/home.tsx
> +      {user && <></>}
Здесь по сути два компонента, которые исключают друг друга. Хочется сделать проверку через if, чтобы читать было удобно.

Еще раньше я еще использовала переменные с `useMemo`, в которой возвращала взаимоисключающие кусочки:
```
const comp = useMemo(() => {
  if (user) {
    return ...
  }
  return ...
}, [])
```
Но такой вариант мне нравится меньше, чем вынести в компонент. `useMemo` все же для вычислений, а не обертка для `UI`.
В твоем случае действительно нет смысла выносить в отдельный компонент все, кроме `main`. Может тернарник тут подошел бы. 
Но можешь оставить как есть. А как компонент будет дописан, станет понятно, нужно ли что-то выносить

2023-02-26 19:52 UTC, skaamoogs commented
Добавил адаптивную ширину контейнера header и footer, ограничил ширину картинки

2023-02-26 21:15 UTC, kate-lozovaya approved these changes
Теперь все отлично!
Спасибо

2023-02-27 04:05 UTC, merged