Feature/mon 41 profile page
22-reactors/monopoly pull request #35
Opened 2023-02-26 06:38 UTC by nullorone

### Рефакторит страницу профиля

Макет - https://www.figma.com/file/vTMj7BiHAG3kx5q66cD1Gk/%D0%9C%D0%BE%D0%BD%D0%BE%D0%BF%D0%BE%D0%BB%D0%B8%D1%8F?node-id=190%3A45773&t=mztEg2wWrUUkEXAv-1

<img width="1136" alt="image" src="https://user-images.githubusercontent.com/35527172/221396138-528f3cbb-7a58-4e39-81cc-4f3b3482bc4a.png">

2023-02-27 12:45 UTC, skaamoogs requested changes
По заданию требуется изменение пароля, думаю, надо это добавить.

Пара вопросов:
1. Подразумевается, что фон будет задаваться в layout?
2. Почему при сохранении настроек профиля происходит переход на предыдущую страницу?

2023-02-27 13:03 UTC, nullorone commented
> По заданию требуется изменение пароля, думаю, надо это добавить.
> 
> Пара вопросов:
> 
> 1. Подразумевается, что фон будет задаваться в layout?
> 2. Почему при сохранении настроек профиля происходит переход на предыдущую страницу?

1) Градиентный фон должен задаваться в main.scss для всех страниц. Будет поправлено в рамках задачи по доработке проекта.

2) Решил сделать возврат на предыдущую страницу, потому что это привычное поведение для пользователя на сайтах. После изменения данных его кидает либо на предыдущую страницу, либо в общие настройки. Иначе получим перерендер компонента с новыми данными и такие мелькания не очень классно смотрятся, на мой взгляд.

2023-02-28 14:15 UTC, skaamoogs commented on packages/client/src/components/info/info.tsx
> +    void navigate(-1);
Получается, валидации введенных данных нет? Независимо от того, что введет пользователь, происходит переход.

2023-02-28 15:04 UTC, nullorone commented on packages/client/src/components/info/info.tsx
> +    void navigate(-1);
увидел, что у тебя в ревью AuthForm есть доработки в валидации. Подожду тогда твоего прохождения ревью и доработаю у себя в профиле

2023-03-09 18:48 UTC, skaamoogs requested changes
Валидация полей есть, а при submit - нет. Т.е. даже если данные невалидны, они все равно отправляются на сервер. При этом со стороны сервера данные не проверяются (проверил), можно туда отправлять пустые строки

2023-03-13 11:52 UTC, skaamoogs approved these changes

2023-03-13 18:44 UTC, kate-lozovaya requested changes

2023-03-13 18:44 UTC, kate-lozovaya commented on packages/client/src/components/avatar/avatar.tsx
> +  }, [props.src]);
[Вопрос]
А зачем дважды подставлять `props.src` в `avatarSrc`? И в инитном значении в `useState`, и в `useEffect`?

2023-03-13 18:44 UTC, kate-lozovaya commented on packages/client/src/components/info/info.module.scss
> +  margin-top: 37px;
[Предложение]
`margin` можно объединить
`margin: 37px auto 0;`

2023-03-13 18:44 UTC, kate-lozovaya commented on packages/client/src/components/input/input.tsx
> +import { ChangeEvent, HTMLProps, useEffect, useRef, useState } from 'react'
[Предложение]
Тут пропал знак `;`.
Лучше прогонять линтер и формат перед коммитом

2023-03-13 18:44 UTC, kate-lozovaya commented on packages/client/src/pages/profile/profile.tsx
> +  const defaultUserFields = useMemo(() => Object.values(FieldMap), []);
[Предложение]
Можно не оборачивать в `useMemo`, а создать до компонента, потому что значение переменной не меняется, ее можно и не пересчитывать.

2023-03-13 18:44 UTC, kate-lozovaya commented on packages/client/src/pages/profile/profile.tsx
> +    }
[Предложение]
`setFields(userFields);` выполняется в любом случае, можно убрать `else`, будет проще читаться
```suggestion
    if (user?.avatar) {
      setAvatar(user.avatar);
    } 
    setFields(userFields);
```

2023-03-14 13:11 UTC, nullorone commented on packages/client/src/components/avatar/avatar.tsx
> +  }, [props.src]);
Потому что вначале приходит пустая строка, а когда данные подтягиваются, то уже приходит строка

2023-03-15 06:54 UTC, kate-lozovaya approved these changes

2023-03-15 06:54 UTC, kate-lozovaya commented on packages/client/src/components/avatar/avatar.tsx
> +  }, [props.src]);
Тогда в useState можно только пустую строку оставить, чтобы не путало

2023-03-15 09:34 UTC, merged