Feature/mon 42 leaderboard page
22-reactors/monopoly pull request #37
Opened 2023-02-26 14:45 UTC by nullorone

### Добавляет страницу leaderboard

макет - https://www.figma.com/file/vTMj7BiHAG3kx5q66cD1Gk/%D0%9C%D0%BE%D0%BD%D0%BE%D0%BF%D0%BE%D0%BB%D0%B8%D1%8F?node-id=185%3A82292&t=6YxJ2ugZp1qfmTJL-1

<img width="1135" alt="image" src="https://user-images.githubusercontent.com/35527172/221417550-175dc4d5-1f3b-4e4e-b861-6eaf9d2779d8.png">

2023-02-26 15:33 UTC, Renovacio3429 approved these changes

2023-02-27 10:26 UTC, kate-lozovaya requested changes

2023-02-27 10:26 UTC, kate-lozovaya commented on packages/client/src/api/leaderboard/interfaces.ts
> +      reactors: ''
[Вопрос]
Почему не `string`?

2023-02-27 10:26 UTC, kate-lozovaya commented on packages/client/src/controllers/leaderboard.ts
> +        console.log(response.reason);
[Вопрос]
Тут в будущем будет генерация ошибки?

2023-02-27 10:26 UTC, kate-lozovaya commented on packages/client/src/utils/helpers.tsx
> +// Разбивает массив на двумерный массив с указанным кол-вом возможной длины
[Предложение]
тут было бы хорошо показать, какой параметр за что отвечает

2023-02-27 10:26 UTC, kate-lozovaya commented on packages/client/src/utils/helpers.tsx
> +  for (let i = 0; i < count; i++) {
[Вопрос]
Почему нужен `count`?
Можно сделать в цикле while - `while next < arr.length`, и тогда весь массив разобьется по лимиту

2023-02-27 10:26 UTC, kate-lozovaya commented on packages/client/src/pages/leaderboard/leaderboard.module.scss
> +  margin-right: auto;
[Предложение]
`margin` можно не разделять по сторонам. Если написать `margin: auto`, будет тоже самое, контейнер встанет в центр

2023-02-28 14:04 UTC, nullorone commented on packages/client/src/controllers/leaderboard.ts
> +        console.log(response.reason);
Да, скорее всего в будущем добавим компонент универсальный, который будет выводить текст ошибки

2023-02-28 14:32 UTC, nullorone commented on packages/client/src/utils/helpers.tsx
> +  for (let i = 0; i < count; i++) {
Да, он лишний.

2023-02-28 14:52 UTC, nullorone commented on packages/client/src/utils/helpers.tsx
> +  for (let i = 0; i < count; i++) {
Но по поводу while, там есть нюанс. Если next будет больше arr.length, а элементы еще останутся, то они просто не попадут в последний массив. Или я не совсем понял, как именно while должен быть реализован

2023-02-28 17:53 UTC, kate-lozovaya commented on packages/client/src/utils/helpers.tsx
> +  for (let i = 0; i < count; i++) {
Да, можно и без while. Видимо так все же удобнее

2023-02-28 17:54 UTC, kate-lozovaya approved these changes

2023-03-01 03:35 UTC, merged