Feature/mon 67 404 500 page refactoring
22-reactors/monopoly pull request #38
Opened 2023-02-26 14:51 UTC by Krezo

### Рефакторинг страницы ошибки

![image](https://user-images.githubusercontent.com/19520555/221417952-45a69a26-e68f-422a-971a-f9d2a9737309.png)

2023-02-27 06:42 UTC, skaamoogs commented on packages/client/src/pages/index.tsx
> +  throw error;
Надо ли, чтобы приложение падало при непредвиденной ошибке? Может лучше ее ловить?

2023-02-27 18:24 UTC, Krezo commented on packages/client/src/pages/index.tsx
> +  throw error;
Почитал доку, возможно и не надо

2023-02-28 08:19 UTC, kate-lozovaya commented on packages/client/src/pages/index.tsx
> +  throw error;
Тут будешь что-то править?

2023-02-28 08:23 UTC, kate-lozovaya requested changes
Непонятен статус по по комментарию коллеги. 
Оставляете так, или сделаете изменение в будущем?

@skaamoogs если все ок, зарезолвь, пожалуйста

2023-02-28 08:26 UTC, Krezo commented on packages/client/src/pages/index.tsx
> +  throw error;
> Тут будешь что-то править?

Да, правки внес

2023-02-28 10:16 UTC, kate-lozovaya approved these changes

2023-02-28 10:17 UTC, merged