Feature/mon 62 auth form component
22-reactors/monopoly pull request #40
Opened 2023-02-27 20:48 UTC by skaamoogs

### Создает компонент AuthForm для страниц Логина и Регистрации
### Подключает валидацию к компоненту AuthForm

<img width="382" alt="Screenshot 2023-02-27 at 23 38 46" src="https://user-images.githubusercontent.com/94950998/221681938-9a0c13fa-eac6-4db6-b8c1-a27aeb674d0e.png"> 
<img width="375" alt="Screenshot 2023-02-27 at 23 46 17" src="https://user-images.githubusercontent.com/94950998/221681987-71e87f81-3381-4a6c-92de-6d3cf2fbf6ac.png">

2023-02-28 10:18 UTC, Krezo requested changes

2023-02-28 10:18 UTC, antonbezushko commented on packages/client/src/components/authForm/authForm.tsx
> +  children: JSX.Element | JSX.Element[];
Неправильный тип children, лучше использывать `PropsWithChildren`

``
```suggestion
  export const AuthForm = (props: PropsWithChildren<IAuthFormProps>) => {
```

2023-02-28 10:18 UTC, antonbezushko commented on packages/client/src/components/authForm/authForm.module.scss
> +  box-sizing: border-box
Можно добавить отступы, иначе выглядит не красиво при заполнении (из-за ошибок формы)

![image](https://user-images.githubusercontent.com/19520555/221794643-6dab0543-96d2-4164-b281-74b5f8925100.png)
```suggestion
.container {
  width: 360px;
  padding: 40px;
  background-color: white;
  border-radius: 10px;
  @include shadowDefault;
  text-align: center;
  margin: 10px 0;
  box-sizing: border-box
```

2023-02-28 14:35 UTC, skaamoogs commented on packages/client/src/components/authForm/authForm.tsx
> +  children: JSX.Element | JSX.Element[];
Сделал

2023-02-28 14:35 UTC, skaamoogs commented on packages/client/src/components/authForm/authForm.module.scss
> +  box-sizing: border-box
Сделал

2023-02-28 17:12 UTC, Krezo approved these changes

2023-02-28 18:11 UTC, kate-lozovaya commented
@Krezo зарезолвь свои вопросы, пожалуйста, если они решены верно

2023-02-28 18:57 UTC, skaamoogs commented
> @Krezo зарезолвь свои вопросы, пожалуйста, если они решены верно

@kate-lozovaya  Он же заэпрувил, или еще резолвить надо?

2023-02-28 19:22 UTC, kate-lozovaya requested changes

2023-02-28 19:22 UTC, kate-lozovaya commented on packages/client/src/components/input/input.tsx
> +  name: string;
[Просто так пишу]
Если делать свой компонент как обертку над стандартным, можно делать его тип как расширение стандартного типа, тогда не пришлось бы добавлять здесь свойство тега input )

2023-02-28 19:22 UTC, kate-lozovaya commented on packages/client/src/components/input/input.module.scss
> +  text-align: left;
[Вопрос]
Изменение этих стилей не ломает внешний вид компонента в других местах использования?

2023-02-28 19:22 UTC, kate-lozovaya commented on packages/client/src/components/authForm/authForm.tsx
> +    });
[Исправление]
Здесь идет проверка `value.errorText`, можно сразу делать цикл по `Object.values(inputValues)`.

И можно посчитать валидность через `every`. Если в каждом значении нет `errorText`, то валидный, иначе - нет
```suggestion
    const isValid = Object.values(inputValues).every(val => !val.errorText)
```

2023-02-28 19:22 UTC, kate-lozovaya commented on packages/client/src/components/authForm/authForm.tsx
> +    }
[Предложение]
Здесь записывается в `setError` отрицание `isValid`, то есть можно записать проще
```suggestion
    setError(!isValid);
```

2023-02-28 19:22 UTC, kate-lozovaya commented on packages/client/src/mocs/registrProps.ts
> +      name: 'second_name',
[Предложение]
Почему `name` тут написан в снейк кейсе, а в 51 строке в камел кейсе? Лучше использовать один вид для оформления

2023-02-28 19:22 UTC, kate-lozovaya commented on packages/client/src/components/authForm/authForm.tsx
> +  const { password, confirmPassword } = inputValues;
[Вопрос]
А что если кто-то случайно или специально поменяет `name` для паролей? Например, сделает `password1` и `password2`

2023-02-28 19:22 UTC, kate-lozovaya commented on packages/client/src/components/authForm/authForm.tsx
> +    });
Здорово, что помнишь про prevState )

2023-02-28 19:22 UTC, kate-lozovaya commented on packages/client/src/components/authForm/authForm.tsx
> +    : undefined;
[Предложение]
Делать два тернарника - не очень хорошо, трудно читается. Здесь можно либо сократить:
```
const errorText = errorTitle ?? error ? 'Ошибка. Проверьте правильность заполнения полей.' : undefined;
```
Но тоже читается так себе.

А можно разбить на два кусочка:
```
const defaultErrorText = error && 'Ошибка. Проверьте правильность заполнения полей.'
const errorText = errorTitle ?? defaultErrorText
```
Если `error` - `false` и `errorTitle`-а нет, то в `defaultErrorText` и `errorText` тоже будут `false`. Что допустимо для кода ниже

2023-02-28 19:22 UTC, kate-lozovaya commented on packages/client/src/components/authForm/authForm.tsx
> +          disabled={errorText ? true : false}
[Предложение]
```suggestion
          disabled={Boolean(errorText)}
```

2023-02-28 19:22 UTC, kate-lozovaya commented on packages/client/src/components/authForm/authForm.module.scss
> +  margin-top: 23px;
[Предложение]
Можно в одно свойство записать
```suggestion
  margin: 23px 0 0;
```

2023-02-28 19:22 UTC, kate-lozovaya commented on packages/client/src/service/validate/validate.ts
> +  }
[Предложение]
Можно сделать объект. Меньше строк занимает, хорошо читается. И `name` судя по функци - `InputId` по типу
```suggestion
  const mapErrorMessage: Record<InputId, string> = {
    [InputId.EMAIL]: ErrorMessages.EMAIL,
    [InputId.LOGIN]: ErrorMessages.LOGIN,
    [InputId.FIRST_NAME]: ErrorMessages.FIRST_NAME,
    [InputId.SECOND_NAME]: ErrorMessages.SECOND_NAME,
    [InputId.PHONE]: ErrorMessages.PHONE,
    [InputId.PASSWORD]: ErrorMessages.PASSWORD,
  }
```

2023-02-28 19:22 UTC, kate-lozovaya commented on packages/client/src/utils/helpers.tsx
> +    return element.props.name as string;
[Вопрос]
Не `InputId` тут будет?

2023-02-28 19:49 UTC, skaamoogs commented on packages/client/src/components/input/input.module.scss
> +  text-align: left;
Ну это стиль ошибки, она в основном здесь используется. Еще в профиле, но там тоже не должно проблем возникнуть

2023-02-28 19:55 UTC, skaamoogs commented on packages/client/src/components/authForm/authForm.tsx
> +    });
Да, так лучше

2023-02-28 19:56 UTC, skaamoogs commented on packages/client/src/components/authForm/authForm.tsx
> +    }
Да, точно

2023-02-28 20:02 UTC, skaamoogs commented on packages/client/src/mocs/registrProps.ts
> +      name: 'second_name',
snake case только в API swagger используется, а так везде camel case

2023-03-01 08:35 UTC, skaamoogs commented on packages/client/src/components/input/input.tsx
> +  name: string;
Согласен

2023-03-01 08:36 UTC, skaamoogs commented on packages/client/src/components/authForm/authForm.tsx
> +  const { password, confirmPassword } = inputValues;
Привязался к enum InputId

2023-03-01 08:36 UTC, skaamoogs commented on packages/client/src/components/authForm/authForm.tsx
> +    : undefined;
Сделал

2023-03-01 09:09 UTC, skaamoogs commented on packages/client/src/utils/helpers.tsx
> +    return element.props.name as string;
Тут проверка, что элемент является компонентом Input

2023-03-01 16:17 UTC, kate-lozovaya commented
> Он же заэпрувил, или еще резолвить надо?

Лучше резолвить, да. Это как показатель того, что вопрос точно решен, и ревьювер это подтвердил

2023-03-01 16:24 UTC, kate-lozovaya commented on packages/client/src/components/input/input.module.scss
> +  text-align: left;
Лучше проверить, что все ок)

2023-03-01 16:29 UTC, skaamoogs commented
> > Он же заэпрувил, или еще резолвить надо?
> 
> Лучше резолвить, да. Это как показатель того, что вопрос точно решен, и ревьювер это подтвердил

Он зарезолвил уже

2023-03-01 16:52 UTC, skaamoogs commented
@kate-lozovaya Можешь заэпрувить? Или что-то нужно еще править?

2023-03-01 16:52 UTC, kate-lozovaya approved these changes

2023-03-01 17:03 UTC, kate-lozovaya commented
> Можешь заэпрувить? Или что-то нужно еще править?
Уже есть

2023-03-01 17:04 UTC, merged