Feature/mon 72 game setup page
22-reactors/monopoly pull request #42
Opened 2023-03-04 16:15 UTC by skaamoogs

### Создает страницу настроек игры
#### Добавляет валидацию ввода настроек
#### Подключает Redux для хранения настроек

### Скриншоты:
<img width="1612" alt="Screenshot 2023-03-04 at 18 56 07" src="https://user-images.githubusercontent.com/94950998/222916783-072fed60-efa4-4efc-9cd9-847e6c53549e.png">

### Видео:
https://user-images.githubusercontent.com/94950998/222916741-98e14f80-00bd-4ce4-a389-2d59e31510d9.mp4

2023-03-07 13:03 UTC, nullorone commented on packages/client/src/components/gameSetup/gameSetup.tsx
> +
лишняя строчка

2023-03-07 13:05 UTC, nullorone commented on packages/client/src/components/gameSetup/players/players.tsx
> +    <>
зачем тут использовать фрагмент?

2023-03-07 13:06 UTC, nullorone commented on packages/client/src/components/input/input.module.scss
> +    position: absolute;
есть миксин absolute()

2023-03-07 13:07 UTC, nullorone commented on packages/client/src/components/select/select.module.scss
> +  z-index: 10;
а почему именно 10?

2023-03-07 13:10 UTC, nullorone commented on packages/client/src/pages/home/home.tsx
> +      {user && <GameSetup maxPlayers={4}/>}
если пользователь авторизован, то его должно просто редиректить на какую-либо страницу. Но я думаю, что содержимое главной должно оставаться и при нажатии на кнопку "Начать игру" его должно вести на страницу настроек

2023-03-07 13:10 UTC, nullorone commented on packages/client/src/reduxstore/players/players.selector.ts
> +export const playersSelector = (state: RootState) => state.players;
а использовать просто useSelector мы сейчас не можем?

2023-03-07 13:13 UTC, nullorone commented on packages/client/src/reduxstore/players/playersSlice.ts
> +
лучше этот файл разделить на доп файлы store.ts и reducers.ts. Этот файл назвать init.ts

2023-03-07 13:14 UTC, nullorone requested changes
добавь пожалуйста сброс select'ов после нажатия на кнопку "Добавить", чтобы пользователю не пришлось стирать поля, перевыбирать

2023-03-09 18:54 UTC, skaamoogs commented on packages/client/src/components/gameSetup/gameSetup.tsx
> +
убрал

2023-03-09 18:54 UTC, skaamoogs commented on packages/client/src/components/gameSetup/players/players.tsx
> +    <>
да, он тут не нужен

2023-03-09 18:55 UTC, skaamoogs commented on packages/client/src/components/input/input.module.scss
> +    position: absolute;
ок. использовал миксин

2023-03-09 18:58 UTC, skaamoogs commented on packages/client/src/reduxstore/players/players.selector.ts
> +export const playersSelector = (state: RootState) => state.players;
Не понял

2023-03-09 19:04 UTC, skaamoogs commented on packages/client/src/pages/home/home.tsx
> +      {user && <GameSetup maxPlayers={4}/>}
Ок. Сделал

2023-03-09 19:11 UTC, skaamoogs commented on packages/client/src/reduxstore/players/playersSlice.ts
> +
объект с редьюсерами вынести? А в store что будет?

2023-03-14 12:56 UTC, nullorone commented on packages/client/src/reduxstore/players/players.selector.ts
> +export const playersSelector = (state: RootState) => state.players;
https://react-redux.js.org/api/hooks#useselector

2023-03-14 12:58 UTC, nullorone commented on packages/client/src/reduxstore/players/playersSlice.ts
> +
initialState. Но это больше как рекомендация. Можешь и не выносить

2023-03-14 12:59 UTC, nullorone approved these changes

2023-03-14 18:07 UTC, kate-lozovaya reviewed
Целая папка задублирована. Поправь, пожалуйста

2023-03-14 18:07 UTC, kate-lozovaya commented on packages/client/src/components/gameSetup/gameSetup.tsx
> +    });
[Предложение]
Функция не зависит ни от чего в компоненте, ее можно вынести из GameSetup, чтобы она не пересоздавалась каждый раз

2023-03-14 18:07 UTC, kate-lozovaya commented on packages/client/src/components/gameSetup/players/players.tsx
> +  for (let i = players.length; i < maxPlayers; i++) {
Когда-то на С++ преподаватель говорил мне, что с `++i` работает быстрее)

2023-03-14 18:07 UTC, kate-lozovaya commented on packages/client/src/components/select/select.module.scss
> +  z-index: 10;
По z-index мне нравится использовать отдельный файл с переменными (главное не сделать их слишком много), где каждая переменная - какой-то уровень.
И удобно их делать не 1 2 3, а по десяткам, или даже по степеням десятки, если переменных немного: 0 1 10 100

2023-03-14 18:07 UTC, kate-lozovaya commented on packages/client/src/components/select/select.tsx
> +    console.log(isOpen);
[Вопрос]
Эти `console.log` были для дебага, или они должны тут быть?

2023-03-14 18:07 UTC, kate-lozovaya commented on packages/client/src/pages/gameSetup/const.ts
> +export const enum Config {
[Вопрос]
Дублирует файл `packages/client/src/components/gameSetup/const.ts`. Так точно должно быть?

2023-03-14 18:07 UTC, kate-lozovaya commented on packages/client/src/pages/gameSetup/gameSetup.module.scss
> +@import '../../styles/globals.scss';
[Вопрос]
Дублирует файл `packages/client/src/components/gameSetup/gameSetup.module.scss`. Так должно быть?

2023-03-14 18:07 UTC, kate-lozovaya commented on packages/client/src/pages/gameSetup/gameSetup.tsx
> +import { useEffect, useState } from 'react';
Тоже копия `packages/client/src/components/gameSetup/gameSetup.tsx`

2023-03-14 18:07 UTC, kate-lozovaya commented on packages/client/src/pages/gameSetup/players/players.module.scss
> +@import '../../../styles/globals.scss';
Дубль `packages/client/src/components/gameSetup/players/players.module.scss`

2023-03-14 18:07 UTC, kate-lozovaya commented on packages/client/src/pages/gameSetup/players/players.tsx
> +import classNames from 'classnames';
Дубль `packages/client/src/components/gameSetup/players/players.tsx`

2023-03-14 19:04 UTC, skaamoogs commented on packages/client/src/components/select/select.tsx
> +    console.log(isOpen);
Да, это я дебажил, забыл убрать

2023-03-14 19:05 UTC, skaamoogs commented
> Целая папка задублирована. Поправь, пожалуйста

Да, она удалена была, видимо после rebase снова появилась.

2023-03-14 19:05 UTC, skaamoogs commented on packages/client/src/components/gameSetup/gameSetup.tsx
> +    });
Ок, вынес

2023-03-15 06:56 UTC, kate-lozovaya approved these changes

2023-03-15 07:06 UTC, merged