add local storage to game
22-reactors/monopoly pull request #43
Opened 2023-03-04 18:48 UTC by Renovacio3429

Хранение состояния игры в localStorage

2023-03-07 12:55 UTC, nullorone commented on packages/client/src/game-engine/core/store/monopolyStore.ts
> +  return localStorageService().get('userConfig');
ты каждый раз вызываешь функцию для доступа к возвращаемым методам. Можно единожды, вне функций вызвать функцию стоража, сохранив в константу и дальше уже обращаться к этой константе

2023-03-07 12:55 UTC, nullorone requested changes
Не пойму, почему не видосе изменение баланса происходит только у одного игрока

2023-03-07 12:59 UTC, Renovacio3429 commented
> Не пойму, почему не видосе изменение баланса происходит только у одного игрока

Они попадали на карты, которые в данные момент ничего не делают, карты которые можно купить имеют полоску

2023-03-07 13:50 UTC, Renovacio3429 commented on packages/client/src/game-engine/core/store/monopolyStore.ts
> +  return localStorageService().get('userConfig');
Попробовал сделать через константы, теперь при нажатии на кнопку "Начать сначало", когда я переинициализирую localStorage, данные в константе не обновляются и игра не стартует заново. Вызовы функции я как раз и cделал, что бы подтягивать всегда актуальные данные из localStorage без побочных эффектов (вполне возможно как-то немного падает производительность из-за такого подхода). По итогу, что бы обновить значения в константе, нужно нажать кнопку "Начать сначало" и перезагрузить страницу, что бы эта переменная снова проинициалировалась и сделала get в localStorage или мне еще нужно как-то следить за обновлением этой переменной.

2023-03-07 14:46 UTC, nullorone approved these changes

2023-03-09 09:02 UTC, kate-lozovaya approved these changes

2023-03-09 09:02 UTC, kate-lozovaya commented on packages/client/src/game-engine/core/winnerinfo/winnerinfo.ts
> +      return !res || user.score > res.score ? user : res;
[Вопрос]
Красиво, что все в одну строчку, но уточни у коллег, комфортно ли им читать такую запись, пожалуйста

2023-03-09 09:02 UTC, kate-lozovaya commented on packages/client/src/pages/game/game.tsx
> +  // HELP!
[Вопрос]
Можешь тут чуть подробнее описать проблему?
Хочешь менять значение переменной `gameEngine` при клике по кнопке?

2023-03-09 09:02 UTC, kate-lozovaya commented on packages/client/src/game-engine/gameEngine.ts
> +      this.chipIndex < getUserConfigStore().length - 1
[Вопрос]
Трижды вызывается `getUserConfigStore`. Тут, в строке 73, в строке 90. Не получится ли создать стор всего один раз? Возникают какие-то проблемы?

2023-03-09 09:02 UTC, kate-lozovaya commented on packages/client/src/game-engine/core/board/gameLoop.ts
> +  }
[Предложение]
Может перенести метод isCardNotBuy в класс для карточки? Кажется, он зависит только от самой карточки и ее состояния в игре

2023-03-09 10:06 UTC, Renovacio3429 commented on packages/client/src/game-engine/gameEngine.ts
> +      this.chipIndex < getUserConfigStore().length - 1
Выше мой коллега предложил вынести эти вызовы localStorage в константу, но появилась проблема при перезагрузке игры, когда я выставляю новые значение пользовательской конфигурации в localStorage, эта константа не подтянет новые данные, пока я не перезагружу страницу. Насколько я понял из документации localStorage это js объект структуры: пара "ключ-значие", то есть он уже в оперативной памяти, а не на диске. Поиск в map O(1). При таком подходе я теряю производительность только когда преобразую строку в объект. На сколько я понял, что бы этого избежать нужно продумать кэширование и его инвалидацию.

2023-03-09 10:12 UTC, Renovacio3429 commented on packages/client/src/pages/game/game.tsx
> +  // HELP!
Когда пользователь заходит на страницу игры вызывается статический метод: GameEngine.init(canvasEl.current);
Этот метод создает экземпляр класса GameEngine и запускает игру.
Ниже есть метод reloadGame(), он предназначен, что бы перезапустить уже запущенную игру по кнопке и его надо вызвать на уже созданном экземпляре классе, который проинициализированом в методе GameEngine.init(canvasEl.current);
Я не понял как это можно сделать с помощью useState (А можно ли?)

То есть мне нужно куда-то положить созданный объект класса, что бы потом вызвать у него метод. Позволяет ли такое сделать react?

2023-03-09 12:37 UTC, kate-lozovaya approved these changes
Ответила в комменте. Можешь попробовать useMemo. Все остальное - ок

2023-03-09 12:37 UTC, kate-lozovaya commented on packages/client/src/pages/game/game.tsx
> +  // HELP!
Тут не нужен `useState`, менять `gameEngine` не нужно.
Можно использовать `useMemo` для получения `gameEngine`, если тебе нужно просто его хранить
```
const gameEngine = useMemo<GameEngineType | null>(async () => {
    if (canvasEl.current) {
        await GameEngine.init(canvasEl.current);
        return await GameEngine.init(canvasEl.current);
    }
    return null;
}, [GameEngine, canvasEl]);
```

2023-03-09 13:57 UTC, merged