Feature/mon 43 forum
22-reactors/monopoly pull request #44
Opened 2023-03-04 20:12 UTC by realdmitrii

Страницы: форума с разделами, раздела с темами, создание темы, тема форума с сообщениями

### Скриншоты
![форум](https://user-images.githubusercontent.com/98462708/222926559-bc5bb2d8-88a9-43a8-ab30-3c75e2393a66.png)
![форум_раздел1](https://user-images.githubusercontent.com/98462708/222926561-4bf05f75-b23d-4ac9-b2fa-4e90a6efb90c.png)
![создать тему](https://user-images.githubusercontent.com/98462708/222926562-61a63e9b-857b-4f94-9974-c71bacd5bf45.png)
![СтраницаТемы](https://user-images.githubusercontent.com/98462708/222926564-d6cf2d66-8c50-497f-818c-c224de18e266.png)

2023-03-05 09:04 UTC, skaamoogs requested changes
Привет. Большой PR получился)
Надо кое-что подправить.
1. Cейчас конфликты есть с dev, сделай rebase.
2. Много задокументрованного кода, надо убрать
3. Используй миксины для текста

Остальное в комментах.

2023-03-05 09:04 UTC, skaamoogs commented on packages/client/src/components/themeMessage/themeMessage.module.scss
> +  //flex-wrap: wrap;
Задокументированный код надо убрать

2023-03-05 09:04 UTC, skaamoogs commented on packages/client/src/pages/forum/ForumSection/index.ts
> +export { ForumSection } from './ForumSection';
Договорились, что импорт компонента делаем без index файла, напрямую из компонента

2023-03-05 09:04 UTC, skaamoogs commented on packages/client/src/mocs/ForumProps.ts
> + // export default ThemeCardProps;
Задокументированный код надо убрать

2023-03-05 09:04 UTC, skaamoogs commented on packages/client/src/pages/forum/ForumSection/ForumSection1.tsx
> +//import { ExampleSection as topicList } from '../ExampleData';
Задокументированный код надо убрать

2023-03-05 09:04 UTC, skaamoogs commented on packages/client/src/pages/forum/ForumTopic/CreateTopic.tsx
> +         <div >
Лишний div

2023-03-05 09:04 UTC, skaamoogs commented on packages/client/src/pages/forum/ForumTopic/ForumTopic1.tsx
> +        <div className={style.topic__name}>
Семантически правильнее будет использовать h2 вместо div

2023-03-05 09:04 UTC, skaamoogs commented on packages/client/src/pages/forum/ForumTopic/ForumTopic1.tsx
> +          {/* Это реализация варианта с составными айди
Не оставляй задокументированный код

2023-03-05 09:04 UTC, skaamoogs commented on packages/client/src/pages/forum/forum.module.scss
> +  position: absolute;
А почему абсолютное позиционирование?

2023-03-05 09:04 UTC, skaamoogs commented on packages/client/src/pages/forum/forum.module.scss
> +  max-width: 1110px;
Для задания ширины контейнера есть mixin, может он подойдет здесь, посмотри.

2023-03-05 09:04 UTC, skaamoogs commented on packages/client/src/pages/forum/forum.module.scss
> +/* H2 */
Для текста есть миксины, воспользуйся ими

2023-03-05 09:04 UTC, skaamoogs commented on packages/client/src/pages/forum/forum.module.scss
> +font-family: 'Manrope';
Для текста есть миксины, воспользуйся ими

2023-03-05 09:04 UTC, skaamoogs commented on packages/client/src/pages/forum/forum.module.scss
> +  font-family: 'Manrope';
Для текста есть миксины, воспользуйся ими

2023-03-05 09:04 UTC, skaamoogs commented on packages/client/src/pages/forum/forum.module.scss
> +    color:#959595;
Для задания цвета есть переменные в globals.scss

2023-03-21 22:06 UTC, realdmitrii commented
> Привет. Большой PR получился) Надо кое-что подправить.
> 
> 1. Cейчас конфликты есть с dev, сделай rebase.
> 2. Много задокументрованного кода, надо убрать
> 3. Используй миксины для текста
> 
> Остальное в комментах.

1-2-3  и комментарии - всё сделал

2023-03-22 08:42 UTC, skaamoogs requested changes
Привет. У тебя ошибки линтера и деплоя. Проект не собирается. Поправь, пожалуйста.

2023-03-22 12:33 UTC, skaamoogs reviewed
Небольшие правки по стилям.

2023-03-22 12:33 UTC, skaamoogs commented on packages/client/src/pages/forum/forum.module.scss
> +      background: $outlined-hover-color;
Не по макету
![2023-03-22_150732](https://user-images.githubusercontent.com/94950998/226902458-139a83fe-b7cd-41ed-9665-8a6d8c66f4e5.png)
Макет:
![2023-03-22_151910](https://user-images.githubusercontent.com/94950998/226903118-a75af924-e1ef-4529-9627-03da72a60e89.png)

2023-03-22 12:33 UTC, skaamoogs commented on packages/client/src/components/themeCard/themeCard.module.scss
> +  flex-direction: row;
А почему поменял?
Теперь не по макету:
![2023-03-22_151124](https://user-images.githubusercontent.com/94950998/226905190-89bb58ae-211d-44cc-96d0-fd1df45e3360.png)
Макет: 
![2023-03-22_152102](https://user-images.githubusercontent.com/94950998/226905567-b9636cc7-2595-40cb-a939-4fae96fdde75.png)
Добавь тогда gap или margin перед lastMessage

2023-03-22 13:04 UTC, realdmitrii commented on packages/client/src/components/themeCard/themeCard.module.scss
> +  flex-direction: row;
поменял, потому что слишком много пустого места, я посчитал что в строчку удобнее для восприятия.
gap наверное поторопился убрать, верну

2023-03-22 13:05 UTC, realdmitrii commented on packages/client/src/pages/forum/forum.module.scss
> +      background: $outlined-hover-color;
ндааа, чот не то пошло) разберусь

2023-03-23 06:24 UTC, skaamoogs approved these changes

2023-03-23 14:22 UTC, kate-lozovaya requested changes

2023-03-23 14:22 UTC, kate-lozovaya commented on packages/client/src/pages/forum/ForumSection/ForumSection1.tsx
> +
[Предложение]
Нужно проверить настройки линтера. Он не должен разрешать три пустых строки ставить

2023-03-23 14:22 UTC, kate-lozovaya commented on packages/client/src/pages/forum/ForumSection/ForumTopicList/ForumTopicList.tsx
> +import { type FC } from 'react';
[Вопрос]
А зачем тут `type`?

2023-03-23 14:22 UTC, kate-lozovaya commented on packages/client/src/pages/forum/ForumSectionList/ForumSectionList.tsx
> +    <div className={style.forum}>
[Предложение]
Тут бы тоже линтером профйтись, криво

2023-03-24 06:35 UTC, realdmitrii commented on packages/client/src/pages/forum/ForumSection/ForumSection1.tsx
> +
три строки убрал, про настройки линтера скажу тимлиду

2023-03-24 06:35 UTC, realdmitrii commented on packages/client/src/pages/forum/ForumSection/ForumTopicList/ForumTopicList.tsx
> +import { type FC } from 'react';
убрал

2023-03-24 06:36 UTC, realdmitrii commented on packages/client/src/pages/forum/ForumSectionList/ForumSectionList.tsx
> +    <div className={style.forum}>
линтер тож ничего не видит. спрямил

2023-03-24 06:36 UTC, realdmitrii commented on packages/client/src/pages/forum/ForumSectionList/ForumSectionList.tsx
> +    <div className={style.forum}>
по настройкам линтера также обсудим с командой

2023-03-24 08:59 UTC, kate-lozovaya requested changes
{ type FC } не в одном месте был. Поправь во всех, пожалуйста

2023-03-27 07:56 UTC, kate-lozovaya approved these changes

2023-03-28 07:08 UTC, merged