Feature/mon 76 game config settings
22-reactors/monopoly pull request #47
Opened 2023-03-15 19:53 UTC by Renovacio3429

[Ссылка на задачу](https://linear.app/monopoly/issue/MON-76/svyazat-nastrojki-konfiga-s-igroj)

Так же добавлены доп. кнопки для продолжения созданной игры и сброса созданных игроков.
P.S. Бот пока не работает

Видео:

https://user-images.githubusercontent.com/59480386/225427083-463957fb-c668-46cf-bdd8-17117a3b70fa.mp4

2023-03-17 13:26 UTC, nullorone commented on packages/client/src/game-engine/config/monopolyConfig.ts
> +    .map(card => card as ICardMainSetting)
тут не совсем понял, ты пробегаешься по массиву и возвращаешь тот же самый массив?

2023-03-17 13:30 UTC, nullorone commented on packages/client/src/pages/gameSetup/players/players.tsx
> +  const playerNotExists = () => {
лучше добавить в название is или has, чтобы было понятно, что функа возвращает булево значение. Сейчас из названия кажется, что функа должна вернуть player

2023-03-17 13:31 UTC, nullorone requested changes
нужны мелкие правки

2023-03-17 20:32 UTC, Renovacio3429 commented on packages/client/src/game-engine/config/monopolyConfig.ts
> +    .map(card => card as ICardMainSetting)
Cначало я привожу карточки к типу к TCardSetting, у которого есть свойство buyingBackgroundColor , а так же исключаю другие типы и если buyingBackgroundColor === true, то это означает, что карточку уже кто-то купил, т.к. при покупке карточки она окрашивается в цвет игрока и таком случае я исключаю данную карточку из полученного массива. В итоге если все карточки куплены (все доступные для покупки карточки покрашены в какие-либо цвета) это означает что игра окончена и нет смысла ее продолжать играть. Согласен что очень не очевидно реализовано.

2023-03-17 20:50 UTC, Renovacio3429 commented on packages/client/src/game-engine/config/monopolyConfig.ts
> +    .map(card => card as ICardMainSetting)
Пример: карт всего 40, из них карт доступных для покупки 22 их мы можем получить через

**getCardsStore()
    .map(card => card as ICardMainSetting)
    .filter(card => card.type === CardTypeEmum.Main);**

А уже дальше мы смотрим, сколько из этих карт куплено (раскрашена она или нет) через свойство **buyingBackgroundColor**

2023-03-20 08:42 UTC, nullorone commented on packages/client/src/game-engine/config/monopolyConfig.ts
> +    .map(card => card as ICardMainSetting)
но ты в этой строчке `.map(card => card as ICardMainSetting)` пробегаешь по всем картам и возвращаешь их же,  никак не изменяя? Просто кастуешь другой интерфейс. Мне кажется, так быть не должно, можно изначально кастануть, что getCardsStore() содержит ICardMainSetting[]

2023-03-20 08:42 UTC, nullorone requested changes
нужно пояснение

2023-03-20 09:48 UTC, Renovacio3429 commented on packages/client/src/game-engine/config/monopolyConfig.ts
> +    .map(card => card as ICardMainSetting)
Убрал лишний map, оказалось я могу полагаться на card.type === CardTypeEmum.Main и type scipt сам понимает что это тип ICardMainSetting т.к. только у него такой enum, не знал что так можно

2023-03-20 09:53 UTC, nullorone approved these changes

2023-03-21 07:43 UTC, kate-lozovaya approved these changes

2023-03-21 07:48 UTC, merged