Feature/mon 71 refactor project
22-reactors/monopoly pull request #48
Opened 2023-03-15 21:03 UTC by nullorone

### Рефакторит проект
Необходимые правки описаны в задаче https://linear.app/monopoly/issue/MON-71/refaktoring-proekta

2023-03-16 11:41 UTC, Renovacio3429 requested changes
Если создать нового юзера через регистраци, отображается что-то не понятное в хедере, где должен быть аватар, а так же в профиле, при смене аватара проблема уходит. Скрин ниже

<img width="1440" alt="Screenshot 2023-03-16 at 18 40 48" src="https://user-images.githubusercontent.com/59480386/225606276-10ef38ff-052b-4357-b05e-6e3d89cb7239.png">

Так же я не совсем понял один момент, я хотел в профиле поменять только свой ник в чате, но мне не позволяет это сделать валидация, которая просит еще и пароль поменять, так и должно быть?

2023-03-16 11:41 UTC, Renovacio3429 commented on packages/client/src/components/avatar/avatar.tsx
> +import { ChangeEvent, useEffect, useRef, useState } from 'react'
';' куда-то пропала

2023-03-16 11:48 UTC, Renovacio3429 commented on packages/client/src/components/footer/footer.tsx
> +                })}
Я, ксати, заметил, что не везде проставляется ';' после форматирования, приходиться в некоторых вручную проставлять, если замечаешь.

2023-03-20 18:51 UTC, Renovacio3429 approved these changes

2023-03-21 07:51 UTC, kate-lozovaya approved these changes
Сложно смотреть на 57 страниц с исправленными отступами и измененными знаками препинания.
Если почти весь PR - автосгенерированн линтером и претиром, небольшие правки верстки (в ней уже все неплохи, вроде), то можно не призывать )

2023-03-21 08:16 UTC, merged