Feature/mon 24 ssr express
22-reactors/monopoly pull request #49
Opened 2023-03-21 15:29 UTC by skaamoogs

### Настройка SSR

#### Настроен Express для режимов dev и production
#### Настроен static data router для SSR

P.S. Redux пока только на клиенте

2023-03-22 09:35 UTC, nullorone commented on packages/client/src/pages/gameSetup/players/players.tsx
> +  });
deps не хватает вроде

2023-03-22 09:37 UTC, nullorone commented on packages/client/ssr.config.ts
> +      formats: ['cjs'],
почему коммон модули, а не ес модули?

2023-03-22 09:39 UTC, nullorone commented on packages/client/vite.config.ts
> +
тут что-то должно быть?

2023-03-22 09:40 UTC, nullorone commented on packages/server/index.ts
> +const isDev = () => process.env.NODE_ENV === 'development';
можно же и без функции узнать в development мы сейчас или нет. Не совсем понял, почему через функцию сделано

2023-03-22 09:42 UTC, nullorone requested changes
мелкие правки

2023-03-22 10:03 UTC, skaamoogs commented on packages/client/src/pages/gameSetup/players/players.tsx
> +  });
У этого кода нет зависимостей. Он должен выполняться после каждого рендера

2023-03-22 10:10 UTC, skaamoogs commented on packages/client/ssr.config.ts
> +      formats: ['cjs'],
В вебинаре так было. Типа Node по умолчанию ES6 не поддерживает

2023-03-22 10:11 UTC, skaamoogs commented on packages/client/vite.config.ts
> +
Нет, убрал

2023-03-22 10:20 UTC, skaamoogs commented on packages/server/index.ts
> +const isDev = () => process.env.NODE_ENV === 'development';
Тоже из вебинара взял. Сделал без функции

2023-03-22 11:49 UTC, nullorone commented on packages/client/src/pages/gameSetup/players/players.tsx
> +  });
если функция должна вызываться при каждом рендере, то зачем её оборачивать в useEffect?

2023-03-22 13:31 UTC, skaamoogs commented on packages/client/src/pages/gameSetup/players/players.tsx
> +  });
Чтобы она вызывалась после того как компонент отрендерился. Это как componentDidMount и componentDidUpdate в классах.

2023-03-22 14:32 UTC, nullorone commented on packages/client/src/pages/gameSetup/players/players.tsx
> +  });
не пойму, почему isGameExist() нельзя подставить сразу на 81 строчку в disabled?

2023-03-22 16:21 UTC, skaamoogs commented on packages/client/src/pages/gameSetup/players/players.tsx
> +  });
Да, так и было. Но при SSR этот код не может выполниться на сервере, т.к. в коде используется localStorage. С useEffect код выполняется уже на клиенте

2023-03-23 12:56 UTC, nullorone requested changes
- необходимо поправить версию ноды для запуска
- необходимо разобраться, почему выпадает ошибка при переходе в "Играть" в хедере

2023-03-25 18:40 UTC, nullorone approved these changes

2023-03-27 08:07 UTC, kate-lozovaya commented on packages/client/src/pages/gameSetup/players/players.tsx
> +  });
В useEffect можно ставить пустой массив, если нужна реакция на каждый рендер, либо можно написать свой хук [useComponentDidMount](https://www.30secondsofcode.org/react/s/use-component-did-mount/)

2023-03-27 08:13 UTC, kate-lozovaya approved these changes

2023-03-27 08:13 UTC, kate-lozovaya commented on packages/client/.eslintignore
> +dist-ssr/
В проект проросли чьи-то [.DS_Store](https://github.com/22-reactors/monopoly/blob/dev/.DS_Store)
Уберите их из проекта и добавьте в игнор. Лучше отдельным ПР

<img width="199" alt="image" src="https://user-images.githubusercontent.com/25737137/227880650-ac762e99-3302-4711-8f35-9a0ee77ffc92.png">

2023-03-27 08:13 UTC, kate-lozovaya commented
Написала коммент про `useEffect`, но он не вошел в ревью

2023-03-27 08:17 UTC, skaamoogs commented on packages/client/.eslintignore
> +dist-ssr/
Они уже в игноре. Надо теперь удалить на github.

2023-03-27 08:26 UTC, skaamoogs commented
> 

Если передать пустой массив в зависимости, то код будет выполняться только при первом рендере. Нам нужно, чтобы код выполнялся при каждом рендере (ре-рендере).

2023-03-27 08:27 UTC, merged