add modal window for buying card
22-reactors/monopoly pull request #50
Opened 2023-03-22 20:17 UTC by Renovacio3429

[Ссылка на задачу](https://linear.app/monopoly/issue/MON-78/uluchshenie-igry)

Добавилось модальное окно для покупки доступных на данный момент для игры карточек (пока их 22).

Видео:

2023-03-23 12:58 UTC, nullorone commented on packages/client/src/components/modal/game/gameModal.module.scss
> +  position: fixed;
а зачем fixed для модалки?

2023-03-23 13:00 UTC, nullorone commented on packages/client/src/components/modal/game/gameModal.tsx
> +        <div className={showHideClassName}>
[Улучшение]
есть html-элемент dialog, который как раз предназначен для модалок. Если захочешь улучшить семантичность, то можно его заюзать.

2023-03-23 13:00 UTC, nullorone commented on packages/client/src/components/modal/game/gameModal.tsx
> +    const { title, children, show, childrenClassName, width } = props;
можно сразу в передаваемых аргументах функции сделать деструктуризацию

2023-03-23 13:02 UTC, nullorone commented on packages/client/src/components/modal/game/gameModal.tsx
> +        width: width ?? 'auto'
не совсем понимаю для какого кейса это нужно

2023-03-23 13:03 UTC, nullorone commented on packages/client/src/components/modal/game/gameModal.tsx
> +    const showHideClassName = classNames(style.modal, show ? style.displayBlock : style.displayNone);
название классов похоже на tailwind) можно просто show ? style.show : style.hide. Потому что хорошая практика скрывать и показывать какой-то элемент не по изменению display, а например по opacity, тогда можно сделать плавное появление и исчезание модалки

2023-03-23 13:08 UTC, nullorone requested changes
небольшие правки

2023-03-23 15:03 UTC, Renovacio3429 commented on packages/client/src/components/modal/game/gameModal.tsx
> +        width: width ?? 'auto'
Убрал, ты прав, динамически она меняться не будет. Идея была в том, что бы настраивать ширину из разных компонентов как мы хотим.

2023-03-23 15:04 UTC, Renovacio3429 commented on packages/client/src/components/modal/game/gameModal.tsx
> +    const showHideClassName = classNames(style.modal, show ? style.displayBlock : style.displayNone);
К сожалению просто show уже есть в пропсах

2023-03-23 15:07 UTC, Renovacio3429 commented on packages/client/src/components/modal/game/gameModal.module.scss
> +  position: fixed;
Сделал absolute и вот что вышло (игра скролиться по оси y, если выйти из fullscreen мода)
<img width="1440" alt="Screenshot 2023-03-23 at 22 05 48" src="https://user-images.githubusercontent.com/59480386/227246287-7739f721-cd92-4ca3-942b-3c4e04b1d364.png">

2023-03-23 15:14 UTC, Renovacio3429 commented on packages/client/src/components/modal/game/gameModal.module.scss
> +  position: fixed;
А это сильно важно, какой position мы выставляем? Если да, то можно сделать enum и вынести его в пропсы, что бы мы могли выбрать нужный position.

2023-03-23 15:46 UTC, nullorone commented on packages/client/src/components/modal/game/gameModal.module.scss
> +  position: fixed;
Судя по твоему вопросу, тебе надо ознакомиться чем позиционирование отличается друг от друга и какое здесь лучше применить

2023-03-23 15:47 UTC, nullorone commented on packages/client/src/components/modal/game/gameModal.tsx
> +    const showHideClassName = classNames(style.modal, show ? style.displayBlock : style.displayNone);
так у тебя будет style.show))

2023-03-23 15:56 UTC, Renovacio3429 commented on packages/client/src/components/modal/game/gameModal.tsx
> +    const showHideClassName = classNames(style.modal, show ? style.displayBlock : style.displayNone);
со стилями я так и сделал, я думал ты про const, которой присваиваются стили

2023-03-23 17:47 UTC, Renovacio3429 commented on packages/client/src/components/modal/game/gameModal.module.scss
> +  position: fixed;
Поправил css

2023-03-24 12:38 UTC, Renovacio3429 commented
> небольшие правки

поправил

2023-03-25 18:41 UTC, nullorone approved these changes

2023-03-27 08:21 UTC, kate-lozovaya approved these changes
Для модального окна можно использовать портал, чтобы он всегда не висел в доме. 
Конкретно в этом проекте можно это не делать, тут только одно модальное окно
[Вот про портал](https://react.dev/reference/react-dom/createPortal)

2023-03-27 08:21 UTC, kate-lozovaya commented on packages/client/src/components/modal/game/gameModal.module.scss
> +  transition: opacity 1s;
[Предложение]
transition  лучше помещать в [`@media (prefers-reduced-motion: no-preference)`](https://doka.guide/a11y/prefers-reduced-motion/), чтобы анимации не было у тех, кто не хочет ее видеть

2023-03-27 09:42 UTC, merged