Feature/mon 29 forum api
22-reactors/monopoly pull request #57
Opened 2023-04-10 20:37 UTC by skaamoogs

### Подключает API к форуму

#### Изменяет модели базы данных форума, api на сервере
#### Создает сервис и контроллер api форума на клиенте
#### Вносит изменения в компонент Форума и его дочерние компоненты

Видео:
https://user-images.githubusercontent.com/94950998/230993141-ae7db0b5-35db-4931-bf6c-286acb62e000.mov

2023-04-13 20:19 UTC, nullorone commented on packages/client/src/pages/forum/forum.module.scss
> +  align-items: left;
такого значения у этого свойства нет. Есть flex-start

2023-04-13 20:21 UTC, nullorone requested changes
поправить css свойство

2023-04-14 07:03 UTC, skaamoogs commented on packages/client/src/pages/forum/forum.module.scss
> +  align-items: left;
Убрал, оно здесь вообще не нужно

2023-04-14 07:45 UTC, nullorone approved these changes

2023-04-14 10:51 UTC, Krezo approved these changes
Рекомедую добавить описание по запуску проекта

2023-04-15 18:49 UTC, kate-lozovaya requested changes

2023-04-15 18:49 UTC, kate-lozovaya commented on packages/client/src/components/themeCard/themeCard.tsx
> +const formatTime = (time?: string) => {
[Вопрос]
А `formatTime` только тут будет? Может вынести?

2023-04-15 18:49 UTC, kate-lozovaya commented on packages/client/src/components/themeMessage/themeMessage.tsx
> +    if (user) {
[Предложение]
Получается большая вложенность. Может лучше выходить на отрицание?
```
if (!user) return;
```

2023-04-15 18:49 UTC, kate-lozovaya commented on packages/client/src/components/themeMessage/themeMessage.tsx
> +        setEmojis(emojis);
[Предложение]
`setEmojis(emojis)` выполняется и в if и в else. Можно поставить после них

2023-04-15 18:49 UTC, kate-lozovaya commented on packages/client/src/pages/forum/ForumSection/ForumSection.tsx
> +                  <ThemeCard {...topic} avatar={avatar} />
[Вопрос]
Тут что-то странное с отступами. Хочется перенести > на новую строку. 
Линтер проходил?

2023-04-17 07:30 UTC, skaamoogs commented on packages/client/src/components/themeCard/themeCard.tsx
> +const formatTime = (time?: string) => {
Ок. Пусть вынесено будет. Просто не знаю, понадобится ли это где-нибудь еще

2023-04-17 07:49 UTC, skaamoogs commented on packages/client/src/pages/forum/ForumSection/ForumSection.tsx
> +                  <ThemeCard {...topic} avatar={avatar} />
Ок

2023-04-17 07:49 UTC, skaamoogs commented on packages/client/src/components/themeMessage/themeMessage.tsx
> +        setEmojis(emojis);
Ок

2023-04-17 08:01 UTC, skaamoogs commented on packages/client/src/pages/forum/ForumSection/ForumSection.tsx
> +                  <ThemeCard {...topic} avatar={avatar} />
Вроде все в порядке. Prettier так форматирует.

2023-04-17 08:34 UTC, skaamoogs commented on packages/client/src/components/themeMessage/themeMessage.tsx
> +    if (user) {
Сделал

2023-04-18 17:28 UTC, kate-lozovaya commented on packages/client/src/pages/forum/ForumSection/ForumSection.tsx
> +                  <ThemeCard {...topic} avatar={avatar} />
ну ладно

2023-04-18 17:29 UTC, kate-lozovaya approved these changes

2023-04-19 12:41 UTC, merged