Feature/mon 81 media api
22-reactors/monopoly pull request #64
Opened 2023-04-24 09:13 UTC by Krezo

### Подключение Media API для воспроизведения звуков в игре (кидание костей, появления сообщения)

https://user-images.githubusercontent.com/19520555/233953080-3cf62415-11b4-4855-91a1-49351b2a51aa.mp4

2023-04-24 11:29 UTC, skaamoogs commented on packages/client/src/service/media/media.ts
> +  console.log(url);
console.log только для дебага нужен или так и задумано?

2023-04-24 11:30 UTC, Krezo commented on packages/client/src/service/media/media.ts
> +  console.log(url);
Правлю

2023-04-24 12:39 UTC, skaamoogs reviewed
Добавь тогда раздачу из папки music, чтобы в production работало

2023-04-25 13:35 UTC, kate-lozovaya requested changes

2023-04-25 13:35 UTC, kate-lozovaya commented on packages/client/src/service/media/media.ts
> +    }
[Предложение]
Может объединить в один if?

```suggestion
    if (!mediaEl) {
      audioElementMap.set(sourceUrl, {
        el: document.createElement('audio'),
        mediaSource: new MediaSource(),
      });
      return;
    }
```

2023-04-25 14:12 UTC, Krezo commented on packages/client/src/service/media/media.ts
> +    }
Нет mediaEl всего будет определен, это чтобы TS не ругался

2023-04-25 14:14 UTC, Krezo commented on packages/client/src/service/media/media.ts
> +    }
Выходить из функции не надо, просто в настройках ts, стоит что нельзя указывать [имя переменной]!, поэтому такое условие

2023-04-25 16:08 UTC, merged